// Trilingua content: grammar rules, quizzes and starter vocabulary
// Each grammar rule: id, cat(egory), title, level (1-3), body (plain text, • bullets), ex (examples [foreign, english]), quiz
const DATA = {
es: {
  name: "Spanish", glyph: "Ñ", tts: "es-ES", accent: "#FFA94D",
  grammar: [
  {id:"es-gender", cat:"Nouns & Articles", title:"Noun gender", level:1,
   body:"Every Spanish noun is masculine or feminine.\n• Most nouns ending in -o are masculine: el libro.\n• Most ending in -a are feminine: la casa.\n• Endings -ción, -sión, -dad, -tad are feminine: la nación, la ciudad.\n• Common exceptions: el día, la mano, el problema, el mapa.",
   ex:[["el libro","the book"],["la casa","the house"],["la ciudad","the city"],["el problema","the problem"]],
   quiz:[
    {q:"Choose the correct article: ___ ciudad", o:["el","la","los","las"], a:1},
    {q:"Choose the correct article: ___ problema", o:["el","la","las","lo"], a:0},
    {q:"Which ending is usually feminine?", o:["-o","-ma","-ción","-or"], a:2}]},
  {id:"es-plural", cat:"Nouns & Articles", title:"Plural of nouns", level:1,
   body:"• Nouns ending in a vowel add -s: libro → libros.\n• Nouns ending in a consonant add -es: ciudad → ciudades.\n• Nouns ending in -z change to -ces: lápiz → lápices.\n• The article changes too: el → los, la → las.",
   ex:[["los libros","the books"],["las ciudades","the cities"],["los lápices","the pencils"]],
   quiz:[
    {q:"Plural of 'la flor'", o:["las flors","las flores","los flores","las florzes"], a:1},
    {q:"Plural of 'el lápiz'", o:["los lápizs","los lápizes","los lápices","las lápices"], a:2},
    {q:"Plural of 'la casa'", o:["las casas","los casas","las cases","la casas"], a:0}]},
  {id:"es-articles", cat:"Nouns & Articles", title:"Definite & indefinite articles", level:1,
   body:"• Definite (the): el, la, los, las.\n• Indefinite (a/an, some): un, una, unos, unas.\n• Article must match gender and number: una mesa, unos amigos.\n• a + el contracts to al; de + el contracts to del.",
   ex:[["un coche","a car"],["unas flores","some flowers"],["Voy al mercado.","I go to the market."],["la puerta del coche","the door of the car"]],
   quiz:[
    {q:"'a + el' contracts to…", o:["ael","al","del","a el (no change)"], a:1},
    {q:"Choose: ___ mesa (a table)", o:["un","una","unos","el"], a:1},
    {q:"Choose: unos ___", o:["casa","amigas","amigos","ciudad"], a:2}]},
  {id:"es-adj", cat:"Adjectives", title:"Adjective agreement", level:1,
   body:"Adjectives agree in gender and number with the noun and usually come after it.\n• -o adjectives have 4 forms: alto, alta, altos, altas.\n• -e or consonant adjectives change only for number: grande → grandes.\n• el chico alto / las chicas altas.",
   ex:[["el gato negro","the black cat"],["las casas blancas","the white houses"],["un problema grande","a big problem"]],
   quiz:[
    {q:"las flores ___ (red)", o:["rojo","roja","rojos","rojas"], a:3},
    {q:"un coche ___ (fast)", o:["rápido","rápida","rápidos","rápidas"], a:0},
    {q:"Adjectives in Spanish usually go…", o:["before the noun","after the noun","at the start","at the end of the sentence"], a:1}]},
  {id:"es-subject-pron", cat:"Pronouns", title:"Subject pronouns", level:1,
   body:"• yo (I), tú (you informal), él/ella/usted (he/she/you formal)\n• nosotros/as (we), vosotros/as (you all, Spain), ellos/ellas/ustedes (they/you all)\n• Subject pronouns are often dropped because the verb ending shows the person: Hablo español = I speak Spanish.",
   ex:[["Yo hablo español.","I speak Spanish."],["¿Tú vives aquí?","Do you live here?"],["Ellas trabajan mucho.","They (f.) work a lot."]],
   quiz:[
    {q:"'we' in Spanish is…", o:["vosotros","nosotros","ellos","ustedes"], a:1},
    {q:"Formal singular 'you' is…", o:["tú","vos","usted","vosotros"], a:2},
    {q:"Why can pronouns be dropped?", o:["they are optional decoration","verb endings show the person","Spanish has no pronouns","only in questions"], a:1}]},
  {id:"es-present", cat:"Verbs", title:"Present tense: regular verbs", level:1,
   body:"Three verb families: -ar, -er, -ir.\n• hablar: hablo, hablas, habla, hablamos, habláis, hablan\n• comer: como, comes, come, comemos, coméis, comen\n• vivir: vivo, vives, vive, vivimos, vivís, viven",
   ex:[["Hablo inglés.","I speak English."],["Comemos a las dos.","We eat at two."],["¿Dónde vives?","Where do you live?"]],
   quiz:[
    {q:"nosotros + comer →", o:["comemos","comen","comimos","comés"], a:0},
    {q:"tú + vivir →", o:["vive","vivas","vives","vivís"], a:2},
    {q:"yo + hablar →", o:["habla","hablo","hablas","hablé"], a:1}]},
  {id:"es-ser-estar", cat:"Verbs", title:"Ser vs. estar (to be)", level:2,
   body:"Two verbs for 'to be'.\n• ser: identity, origin, profession, permanent traits, time. Soy médico. Es de México.\n• estar: location, temporary states, feelings, ongoing actions. Estoy cansado. Está en casa.\n• Some adjectives change meaning: ser aburrido (boring) vs estar aburrido (bored).",
   ex:[["Soy estudiante.","I am a student."],["Estoy en el trabajo.","I am at work."],["La sopa está fría.","The soup is cold (right now)."]],
   quiz:[
    {q:"'I am tired' →", o:["Soy cansado","Estoy cansado","Es cansado","Está cansado"], a:1},
    {q:"'She is from Spain' →", o:["Está de España","Es de España","Estás de España","Era en España"], a:1},
    {q:"Location uses…", o:["ser","estar","either","haber"], a:1}]},
  {id:"es-irregular", cat:"Verbs", title:"Key irregular presents", level:2,
   body:"• tener (to have): tengo, tienes, tiene…  ir (to go): voy, vas, va…\n• hacer (to do/make): hago…  poder (can): puedo, puedes…\n• querer (to want): quiero…  Stem changes e→ie, o→ue are common: pensar → pienso, dormir → duermo.",
   ex:[["Tengo dos hermanos.","I have two brothers."],["Vamos al cine.","We go to the cinema."],["¿Puedes ayudarme?","Can you help me?"]],
   quiz:[
    {q:"yo + tener →", o:["teno","tengo","tiengo","tengoy"], a:1},
    {q:"nosotros + ir →", o:["imos","vamos","van","voy"], a:1},
    {q:"'dormir' with yo →", o:["dormo","duermo","dormío","duero"], a:1}]},
  {id:"es-preterite", cat:"Verbs", title:"Preterite (simple past)", level:2,
   body:"For completed past actions.\n• hablar: hablé, hablaste, habló, hablamos, hablasteis, hablaron\n• comer/vivir: comí, comiste, comió, comimos, comisteis, comieron\n• Irregulars: fui (ser/ir), tuve (tener), hice (hacer), estuve (estar).",
   ex:[["Ayer hablé con Ana.","Yesterday I spoke with Ana."],["Comieron en casa.","They ate at home."],["Fui a Madrid.","I went to Madrid."]],
   quiz:[
    {q:"'I ate' →", o:["comí","comía","como","comé"], a:0},
    {q:"'she spoke' →", o:["habla","hablé","habló","hablaba"], a:2},
    {q:"'I went' →", o:["iba","fui","voy","fue"], a:1}]},
  {id:"es-imperfect", cat:"Verbs", title:"Imperfect past", level:2,
   body:"For habits, descriptions and background in the past ('used to', 'was …ing').\n• hablar: hablaba, hablabas, hablaba, hablábamos, hablabais, hablaban\n• comer/vivir: comía, comías…\n• Only 3 irregulars: ser (era), ir (iba), ver (veía).",
   ex:[["De niño jugaba al fútbol.","As a child I used to play football."],["Llovía mucho.","It was raining a lot."],["Éramos amigos.","We were friends."]],
   quiz:[
    {q:"Habitual past actions use…", o:["preterite","imperfect","future","subjunctive"], a:1},
    {q:"'I used to live' →", o:["viví","vivía","vivo","viviera"], a:1},
    {q:"Imperfect of ser (yo) →", o:["fui","era","estaba","sería"], a:1}]},
  {id:"es-future", cat:"Verbs", title:"Future & 'ir a' future", level:2,
   body:"• Simple future: infinitive + é, ás, á, emos, éis, án. hablaré = I will speak.\n• Irregular stems: tendré (tener), haré (hacer), podré (poder), diré (decir).\n• Near future: ir a + infinitive. Voy a comer = I'm going to eat.",
   ex:[["Mañana trabajaré.","Tomorrow I will work."],["Vamos a viajar.","We are going to travel."],["Tendrás tiempo.","You will have time."]],
   quiz:[
    {q:"'I will speak' →", o:["hablo","hablaré","hablaría","hablaba"], a:1},
    {q:"Near future uses…", o:["ir a + infinitive","estar + gerundio","haber + participio","ser + de"], a:0},
    {q:"Future stem of 'tener' →", o:["ten-","tener-","tendr-","tien-"], a:2}]},
  {id:"es-reflexive", cat:"Verbs", title:"Reflexive verbs", level:2,
   body:"Action done to oneself: pronoun + verb.\n• me, te, se, nos, os, se.\n• levantarse: me levanto (I get up), te levantas…\n• Common: ducharse, llamarse, sentarse, acostarse. Me llamo Ana = My name is Ana.",
   ex:[["Me levanto a las siete.","I get up at seven."],["¿Cómo te llamas?","What's your name?"],["Se ducha por la mañana.","He showers in the morning."]],
   quiz:[
    {q:"'I get up' →", o:["levanto","me levanto","se levanto","me levantas"], a:1},
    {q:"Reflexive pronoun for nosotros →", o:["se","os","nos","me"], a:2},
    {q:"'¿Cómo ___ llamas?'", o:["me","te","se","nos"], a:1}]},
  {id:"es-gustar", cat:"Verbs", title:"Gustar (to like)", level:2,
   body:"Literally 'to be pleasing'. The thing liked is the subject.\n• me gusta + singular / me gustan + plural.\n• me, te, le, nos, os, les + gusta(n).\n• Me gusta el café. Me gustan los perros. A ella le gusta bailar.",
   ex:[["Me gusta el café.","I like coffee."],["Nos gustan las películas.","We like movies."],["¿Te gusta viajar?","Do you like traveling?"]],
   quiz:[
    {q:"'I like dogs' →", o:["Me gusta los perros","Me gustan los perros","Gusto los perros","Me gustan perro"], a:1},
    {q:"'She likes music' →", o:["Le gusta la música","Se gusta la música","La gusta música","Le gustan la música"], a:0},
    {q:"gustan is used when…", o:["the liker is plural","the thing liked is plural","always","in questions"], a:1}]},
  {id:"es-porpara", cat:"Prepositions", title:"Por vs. para", level:3,
   body:"• para: purpose/goal, recipient, deadline, destination. Es para ti. Estudio para aprender.\n• por: cause/reason, exchange, duration, movement through, 'by'. Gracias por todo. Pasamos por el parque.\n",
   ex:[["Este regalo es para ti.","This gift is for you."],["Gracias por tu ayuda.","Thanks for your help."],["Caminamos por la ciudad.","We walk through the city."]],
   quiz:[
    {q:"Purpose ('in order to') →", o:["por","para","de","a"], a:1},
    {q:"'Thanks ___ everything'", o:["para","por","de","con"], a:1},
    {q:"Deadline ('by Friday') →", o:["por el viernes","para el viernes","en viernes","a viernes"], a:1}]},
  {id:"es-negation", cat:"Sentences", title:"Negation & questions", level:1,
   body:"• Negation: put no before the verb. No hablo francés.\n• Double negatives are correct: No veo nada (I see nothing).\n• Questions: invert or just use intonation + ¿…?  ¿Hablas inglés?\n• Question words: qué, quién, dónde, cuándo, por qué, cómo, cuánto.",
   ex:[["No tengo tiempo.","I don't have time."],["No hay nadie aquí.","There is nobody here."],["¿Dónde está el baño?","Where is the bathroom?"]],
   quiz:[
    {q:"'I don't understand' →", o:["Entiendo no","No entiendo","Yo no entender","Entiendo nada"], a:1},
    {q:"'where' →", o:["cuándo","cómo","dónde","quién"], a:2},
    {q:"'No veo nada' means…", o:["I see nothing","I don't see anything wrong","I always see","I see everything"], a:0}]},
  {id:"es-subjunctive", cat:"Verbs", title:"Present subjunctive (intro)", level:3,
   body:"Used after wishes, doubt, emotion: quiero que, espero que, dudo que…\n• Form: take yo-present, drop -o, add opposite endings. hablar → hable; comer → coma.\n• Quiero que vengas = I want you to come.\n• Irregulars: sea (ser), vaya (ir), tenga (tener), haga (hacer).",
   ex:[["Espero que estés bien.","I hope you are well."],["Quiero que vengas.","I want you to come."],["Dudo que sea verdad.","I doubt it's true."]],
   quiz:[
    {q:"Subjunctive of hablar (él) →", o:["habla","hable","hablará","hablaba"], a:1},
    {q:"'Quiero que ___ (venir, tú)'", o:["vienes","vengas","venir","vendrás"], a:1},
    {q:"Subjunctive follows…", o:["facts","wishes & doubt","past events","commands only"], a:1}]}
  ],
  vocab: [
   {w:"hola",t:"hello",c:"basics"},{w:"gracias",t:"thank you",c:"basics"},{w:"por favor",t:"please",c:"basics"},
   {w:"sí",t:"yes",c:"basics"},{w:"no",t:"no",c:"basics"},{w:"adiós",t:"goodbye",c:"basics"},
   {w:"el agua",t:"water",c:"food"},{w:"el pan",t:"bread",c:"food"},{w:"la leche",t:"milk",c:"food"},
   {w:"la manzana",t:"apple",c:"food"},{w:"el café",t:"coffee",c:"food"},{w:"la cerveza",t:"beer",c:"food"},
   {w:"la casa",t:"house",c:"places"},{w:"la ciudad",t:"city",c:"places"},{w:"la calle",t:"street",c:"places"},
   {w:"el mercado",t:"market",c:"places"},{w:"la playa",t:"beach",c:"places"},
   {w:"el amigo",t:"friend",c:"people"},{w:"la familia",t:"family",c:"people"},{w:"el hombre",t:"man",c:"people"},
   {w:"la mujer",t:"woman",c:"people"},{w:"el niño",t:"child",c:"people"},
   {w:"hablar",t:"to speak",c:"verbs"},{w:"comer",t:"to eat",c:"verbs"},{w:"vivir",t:"to live",c:"verbs"},
   {w:"tener",t:"to have",c:"verbs"},{w:"ir",t:"to go",c:"verbs"},{w:"querer",t:"to want",c:"verbs"},
   {w:"hacer",t:"to do / make",c:"verbs"},{w:"poder",t:"to be able to",c:"verbs"},
   {w:"grande",t:"big",c:"adjectives"},{w:"pequeño",t:"small",c:"adjectives"},{w:"bueno",t:"good",c:"adjectives"},
   {w:"malo",t:"bad",c:"adjectives"},{w:"rápido",t:"fast",c:"adjectives"},{w:"bonito",t:"pretty",c:"adjectives"},
   {w:"hoy",t:"today",c:"time"},{w:"mañana",t:"tomorrow",c:"time"},{w:"ayer",t:"yesterday",c:"time"},
   {w:"ahora",t:"now",c:"time"},{w:"siempre",t:"always",c:"time"},{w:"nunca",t:"never",c:"time"}
  ]
},
de: {
  name: "German", glyph: "ß", tts: "de-DE", accent: "#74C0FC",
  grammar: [
  {id:"de-gender", cat:"Nouns & Articles", title:"Noun gender: der, die, das", level:1,
   body:"Every German noun has one of three genders and is always capitalized.\n• der (masculine): der Mann, der Tisch\n• die (feminine): die Frau, die Lampe\n• das (neuter): das Kind, das Buch\n• Hints: -ung, -heit, -keit, -schaft → die; -chen, -lein → das; -er (people) → often der.",
   ex:[["der Tisch","the table"],["die Lampe","the lamp"],["das Buch","the book"],["die Zeitung","the newspaper"]],
   quiz:[
    {q:"___ Buch", o:["der","die","das","den"], a:2},
    {q:"Nouns ending in -ung are usually…", o:["der","die","das","plural only"], a:1},
    {q:"___ Mädchen (girl, ends in -chen)", o:["der","die","das","den"], a:2}]},
  {id:"de-plural", cat:"Nouns & Articles", title:"Plural forms", level:1,
   body:"Plurals vary; the article is always die.\n• -e: der Tisch → die Tische\n• -er (+umlaut): das Kind → die Kinder, das Buch → die Bücher\n• -n/-en: die Lampe → die Lampen\n• -s (loanwords): das Auto → die Autos\n• Learn the plural with each noun.",
   ex:[["die Bücher","the books"],["die Kinder","the children"],["die Autos","the cars"]],
   quiz:[
    {q:"Plural article is always…", o:["der","die","das","den"], a:1},
    {q:"Plural of 'das Buch'", o:["die Buchs","die Bücher","die Buche","die Büchen"], a:1},
    {q:"Plural of 'das Auto'", o:["die Autoen","die Autos","die Autor","die Äuto"], a:1}]},
  {id:"de-cases", cat:"Cases", title:"The four cases (overview)", level:2,
   body:"German marks the role of a noun with cases, mainly via the article.\n• Nominative = subject: Der Mann schläft.\n• Accusative = direct object: Ich sehe den Mann.\n• Dative = indirect object: Ich gebe dem Mann das Buch.\n• Genitive = possession: das Auto des Mannes.\nMasculine changes most: der → den → dem → des.",
   ex:[["Der Hund schläft.","The dog sleeps. (nom.)"],["Ich sehe den Hund.","I see the dog. (acc.)"],["Ich gebe dem Hund Wasser.","I give the dog water. (dat.)"]],
   quiz:[
    {q:"Direct object takes…", o:["nominative","accusative","dative","genitive"], a:1},
    {q:"'Ich sehe ___ Mann.'", o:["der","den","dem","des"], a:1},
    {q:"'Ich helfe ___ Frau.' (helfen + dative)", o:["die","der","den","das"], a:1}]},
  {id:"de-akkusativ", cat:"Cases", title:"Accusative in detail", level:2,
   body:"Only masculine articles change in accusative.\n• der → den, ein → einen. die/das stay the same.\n• Ich habe einen Hund. Ich sehe den Film.\n• Accusative prepositions: durch, für, gegen, ohne, um.",
   ex:[["Ich habe einen Bruder.","I have a brother."],["Das Geschenk ist für dich.","The gift is for you."],["Wir gehen ohne den Hund.","We go without the dog."]],
   quiz:[
    {q:"'Ich habe ___ Hund.'", o:["ein","einen","einem","eines"], a:1},
    {q:"Which preposition takes accusative?", o:["mit","für","aus","bei"], a:1},
    {q:"Accusative of 'die Frau'", o:["die Frau","der Frau","den Frau","dem Frau"], a:0}]},
  {id:"de-dativ", cat:"Cases", title:"Dative in detail", level:2,
   body:"• der/das → dem, die → der, plural → den + n on the noun.\n• Dative prepositions: aus, bei, mit, nach, seit, von, zu.\n• Dative verbs: helfen, danken, gefallen, gehören.\n• Ich fahre mit dem Bus. Das Buch gehört der Frau.",
   ex:[["Ich fahre mit dem Bus.","I go by bus."],["Wir helfen den Kindern.","We help the children."],["Sie kommt aus der Schweiz.","She comes from Switzerland."]],
   quiz:[
    {q:"'mit' always takes…", o:["accusative","dative","genitive","nominative"], a:1},
    {q:"'Ich helfe ___ Mann.'", o:["der","den","dem","des"], a:2},
    {q:"Dative plural of 'die Kinder'", o:["die Kinder","den Kindern","der Kinder","dem Kinder"], a:1}]},
  {id:"de-present", cat:"Verbs", title:"Present tense", level:1,
   body:"• machen: ich mache, du machst, er/sie/es macht, wir machen, ihr macht, sie machen\n• Stem changes in du/er: fahren → du fährst; sprechen → du sprichst; lesen → du liest.\n• sein: bin, bist, ist, sind, seid, sind. haben: habe, hast, hat…",
   ex:[["Ich mache Kaffee.","I make coffee."],["Du sprichst gut Deutsch.","You speak German well."],["Wir sind müde.","We are tired."]],
   quiz:[
    {q:"du + fahren →", o:["fahrst","fährst","fahrt","fährt"], a:1},
    {q:"ich + sein →", o:["bist","bin","ist","sein"], a:1},
    {q:"er + haben →", o:["habt","habe","hat","hast"], a:2}]},
  {id:"de-wordorder", cat:"Word order", title:"Verb-second (V2) rule", level:2,
   body:"In main clauses the conjugated verb is always in position 2.\n• Ich gehe heute ins Kino.\n• Heute gehe ich ins Kino. (time first → verb still 2nd, subject moves)\n• Yes/no questions: verb first. Gehst du ins Kino?",
   ex:[["Heute lerne ich Deutsch.","Today I'm learning German."],["Morgen fahren wir nach Berlin.","Tomorrow we're driving to Berlin."],["Trinkst du Kaffee?","Do you drink coffee?"]],
   quiz:[
    {q:"'Heute ___ ich Deutsch.'", o:["ich lerne","lerne","lernen","lernt"], a:1},
    {q:"In a main clause, the verb is in position…", o:["1","2","3","last"], a:1},
    {q:"Yes/no questions put the verb…", o:["last","second","first","anywhere"], a:2}]},
  {id:"de-nebensatz", cat:"Word order", title:"Subordinate clauses: verb last", level:3,
   body:"After weil, dass, wenn, obwohl … the conjugated verb goes to the end.\n• Ich bleibe zu Hause, weil ich krank bin.\n• Er sagt, dass er morgen kommt.\n• If the subordinate clause comes first, the main verb follows immediately: Weil ich krank bin, bleibe ich zu Hause.",
   ex:[["Ich lerne Deutsch, weil es Spaß macht.","I learn German because it's fun."],["Ich weiß, dass du recht hast.","I know that you are right."]],
   quiz:[
    {q:"'…, weil ich müde ___.'", o:["bin","ich bin","bin ich","sein"], a:0},
    {q:"After 'dass' the verb goes…", o:["first","second","to the end","before the subject"], a:2},
    {q:"Which word starts a subordinate clause?", o:["und","aber","weil","denn"], a:2}]},
  {id:"de-modal", cat:"Verbs", title:"Modal verbs", level:2,
   body:"können (can), müssen (must), wollen (want), dürfen (may), sollen (should), mögen (like).\n• Modal in position 2, main verb as infinitive at the end.\n• Ich kann gut schwimmen. Du musst heute arbeiten.\n• ich/er forms are identical: ich kann, er kann.",
   ex:[["Ich kann schwimmen.","I can swim."],["Wir müssen jetzt gehen.","We have to go now."],["Darf ich fragen?","May I ask?"]],
   quiz:[
    {q:"'Ich ___ Deutsch sprechen.' (can)", o:["kann","kannst","können","könnt"], a:0},
    {q:"With modals, the main verb goes…", o:["second","to the end as infinitive","first","is dropped"], a:1},
    {q:"'must' →", o:["dürfen","sollen","müssen","mögen"], a:2}]},
  {id:"de-perfekt", cat:"Verbs", title:"Perfect tense (spoken past)", level:2,
   body:"haben/sein + past participle at the end. Standard past in conversation.\n• Ich habe Pizza gegessen. \n• sein with movement/change: Ich bin nach Hause gegangen.\n• Participles: ge…t (gemacht), ge…en (gesehen); verbs in -ieren: studiert (no ge-).",
   ex:[["Ich habe gearbeitet.","I worked / have worked."],["Er ist gekommen.","He came."],["Wir haben das Buch gelesen.","We read the book."]],
   quiz:[
    {q:"'Ich ___ nach Berlin gefahren.'", o:["habe","bin","ist","war"], a:1},
    {q:"Participle of 'machen'", o:["gemacht","machte","gemachen","macht"], a:0},
    {q:"Verbs ending in -ieren form the participle…", o:["with ge-","without ge-","with -en","irregularly always"], a:1}]},
  {id:"de-praeteritum", cat:"Verbs", title:"Simple past: war & hatte", level:2,
   body:"In speech, sein and haben usually use simple past instead of perfect.\n• sein: ich war, du warst, er war, wir waren…\n• haben: ich hatte, du hattest, er hatte…\n• Es war schön. Ich hatte keine Zeit.",
   ex:[["Ich war gestern krank.","I was sick yesterday."],["Wir hatten viel Spaß.","We had a lot of fun."]],
   quiz:[
    {q:"'I was' →", o:["ich bin gewesen (only)","ich war","ich wurde","ich hätte"], a:1},
    {q:"'wir ___ keine Zeit' (had)", o:["hatten","haben","hatte","waren"], a:0},
    {q:"'du ___ müde' (were)", o:["warst","war","bist","wurdest"], a:0}]},
  {id:"de-separable", cat:"Verbs", title:"Separable verbs", level:2,
   body:"Prefix splits off and goes to the end in the present.\n• aufstehen: Ich stehe um 7 Uhr auf.\n• anrufen: Ich rufe dich morgen an.\n• Common prefixes: auf-, an-, ein-, mit-, aus-, zu-. In the participle, ge- goes inside: aufgestanden.",
   ex:[["Ich stehe früh auf.","I get up early."],["Er ruft mich an.","He calls me."],["Machst du das Fenster zu?","Are you closing the window?"]],
   quiz:[
    {q:"'aufstehen' in a sentence: Ich ___ um 7 ___.", o:["aufstehe / –","stehe / auf","auf / stehe","stehe auf / –"], a:1},
    {q:"Participle of 'aufstehen'", o:["geaufstanden","aufgestanden","aufstanden","gestandenauf"], a:1},
    {q:"Where does the prefix go in the present?", o:["stays attached","to the end","before the subject","is dropped"], a:1}]},
  {id:"de-negation", cat:"Sentences", title:"Negation: nicht vs. kein", level:1,
   body:"• kein negates nouns with ein or no article: Ich habe kein Auto.\n• nicht negates verbs, adjectives, and nouns with definite article: Ich komme nicht. Das ist nicht das richtige Buch.\n• kein takes the same endings as ein: keinen, keiner, keinem…",
   ex:[["Ich habe keine Zeit.","I have no time."],["Er kommt nicht.","He isn't coming."],["Das ist kein Problem.","That's no problem."]],
   quiz:[
    {q:"'I have no car' →", o:["Ich habe nicht Auto","Ich habe kein Auto","Ich habe keines Auto","Ich nicht habe Auto"], a:1},
    {q:"Negate a verb with…", o:["kein","nicht","nein","nichts"], a:1},
    {q:"'Ich habe ___ Hund.' (no dog, acc. masc.)", o:["kein","keine","keinen","keinem"], a:2}]},
  {id:"de-adjektiv", cat:"Adjectives", title:"Adjective endings (intro)", level:3,
   body:"Adjectives before a noun take endings depending on article and case.\n• After der/die/das (nominative): -e. der große Hund, die kleine Katze.\n• After ein: masculine -er, neuter -es. ein großer Hund, ein kleines Kind.\n• Predicative adjectives don't change: Der Hund ist groß.",
   ex:[["der große Hund","the big dog"],["ein kleines Kind","a small child"],["Die Katze ist klein.","The cat is small."]],
   quiz:[
    {q:"'ein groß___ Hund' (nom.)", o:["-e","-er","-es","-en"], a:1},
    {q:"'die klein___ Katze' (nom.)", o:["-e","-er","-es","-en"], a:0},
    {q:"After 'ist', the adjective…", o:["takes -e","takes -en","has no ending","agrees in case"], a:2}]},
  {id:"de-wechsel", cat:"Prepositions", title:"Two-way prepositions", level:3,
   body:"in, an, auf, über, unter, vor, hinter, neben, zwischen take:\n• Accusative for movement/direction (wohin?): Ich gehe in die Stadt.\n• Dative for location (wo?): Ich bin in der Stadt.\n",
   ex:[["Ich gehe in die Küche.","I go into the kitchen. (acc.)"],["Ich bin in der Küche.","I am in the kitchen. (dat.)"],["Die Lampe hängt über dem Tisch.","The lamp hangs above the table."]],
   quiz:[
    {q:"Movement (wohin?) takes…", o:["dative","accusative","genitive","nominative"], a:1},
    {q:"'Ich bin in ___ Stadt.'", o:["die","der","dem","das"], a:1},
    {q:"'Wir fahren an ___ Meer.' (to the sea, das Meer)", o:["das","dem","der","den"], a:0}]},
  {id:"de-questions", cat:"Sentences", title:"Question words", level:1,
   body:"• wer (who), was (what), wo (where), wohin (where to), wann (when), warum (why), wie (how), wie viel (how much).\n• W-questions: question word + verb + subject. Wo wohnst du?\n• wer declines: wen (acc.), wem (dat.).",
   ex:[["Wo wohnst du?","Where do you live?"],["Warum lernst du Deutsch?","Why are you learning German?"],["Wie viel kostet das?","How much does that cost?"]],
   quiz:[
    {q:"'when' →", o:["wann","wenn","wo","wie"], a:0},
    {q:"'Wo ___ du?' (live)", o:["wohnen","wohnst","wohnt","wohne"], a:1},
    {q:"Accusative of 'wer' →", o:["wem","wen","wessen","wer"], a:1}]}
  ],
  vocab: [
   {w:"hallo",t:"hello",c:"basics"},{w:"danke",t:"thank you",c:"basics"},{w:"bitte",t:"please / you're welcome",c:"basics"},
   {w:"ja",t:"yes",c:"basics"},{w:"nein",t:"no",c:"basics"},{w:"tschüss",t:"bye",c:"basics"},
   {w:"das Wasser",t:"water",c:"food"},{w:"das Brot",t:"bread",c:"food"},{w:"die Milch",t:"milk",c:"food"},
   {w:"der Apfel",t:"apple",c:"food"},{w:"der Kaffee",t:"coffee",c:"food"},{w:"das Bier",t:"beer",c:"food"},
   {w:"das Haus",t:"house",c:"places"},{w:"die Stadt",t:"city",c:"places"},{w:"die Straße",t:"street",c:"places"},
   {w:"der Bahnhof",t:"train station",c:"places"},{w:"der Markt",t:"market",c:"places"},
   {w:"der Freund",t:"friend (m.)",c:"people"},{w:"die Familie",t:"family",c:"people"},{w:"der Mann",t:"man",c:"people"},
   {w:"die Frau",t:"woman",c:"people"},{w:"das Kind",t:"child",c:"people"},
   {w:"sprechen",t:"to speak",c:"verbs"},{w:"essen",t:"to eat",c:"verbs"},{w:"wohnen",t:"to live (reside)",c:"verbs"},
   {w:"haben",t:"to have",c:"verbs"},{w:"gehen",t:"to go",c:"verbs"},{w:"wollen",t:"to want",c:"verbs"},
   {w:"machen",t:"to do / make",c:"verbs"},{w:"können",t:"to be able to",c:"verbs"},
   {w:"groß",t:"big",c:"adjectives"},{w:"klein",t:"small",c:"adjectives"},{w:"gut",t:"good",c:"adjectives"},
   {w:"schlecht",t:"bad",c:"adjectives"},{w:"schnell",t:"fast",c:"adjectives"},{w:"schön",t:"beautiful",c:"adjectives"},
   {w:"heute",t:"today",c:"time"},{w:"morgen",t:"tomorrow",c:"time"},{w:"gestern",t:"yesterday",c:"time"},
   {w:"jetzt",t:"now",c:"time"},{w:"immer",t:"always",c:"time"},{w:"nie",t:"never",c:"time"}
  ]
},
ja: {
  name: "Japanese", glyph: "あ", tts: "ja-JP", accent: "#FF6B6B",
  grammar: [
  {id:"ja-writing", cat:"Writing", title:"Three writing systems", level:1,
   body:"• Hiragana (ひらがな): native words and grammar endings. あ, い, う…\n• Katakana (カタカナ): foreign loanwords and emphasis. コーヒー = coffee.\n• Kanji (漢字): Chinese characters for word roots. 日本 = Japan.\nSentences mix all three: 私はコーヒーを飲みます。",
   ex:[["ひらがな (hiragana)","native syllabary"],["カタカナ (katakana)","loanword syllabary"],["漢字 (kanji)","Chinese characters"]],
   quiz:[
    {q:"Loanwords like 'coffee' are written in…", o:["hiragana","katakana","kanji","romaji"], a:1},
    {q:"Grammar endings are written in…", o:["hiragana","katakana","kanji","numbers"], a:0},
    {q:"漢字 are…", o:["a syllabary","Chinese characters","punctuation","only names"], a:1}]},
  {id:"ja-sov", cat:"Sentences", title:"Word order: SOV", level:1,
   body:"The verb always comes last: Subject – Object – Verb.\n• わたしは みずを のみます。(watashi wa mizu o nomimasu) = I drink water.\n• Particles after each word mark its role, so word order before the verb is flexible.",
   ex:[["わたしはみずをのみます。","I drink water."],["ねこはさかなをたべます。","The cat eats fish."]],
   quiz:[
    {q:"The Japanese verb goes…", o:["first","second","last","anywhere"], a:2},
    {q:"'I eat bread' order:", o:["eat–I–bread","I–bread–eat","bread–eat–I","I–eat–bread"], a:1},
    {q:"Roles of words are marked by…", o:["word order only","particles","endings on nouns","tone"], a:1}]},
  {id:"ja-wa-ga", cat:"Particles", title:"は (wa) and が (ga)", level:2,
   body:"• は marks the topic: what the sentence is about. わたしは がくせいです。(As for me, I'm a student.)\n• が marks the grammatical subject, new information, or emphasis: だれが きましたか。(Who came?)\n• Written は but pronounced 'wa' when used as a particle.",
   ex:[["わたしは がくせいです。","I am a student."],["ねこが います。","There is a cat."],["だれが きましたか。","Who came?"]],
   quiz:[
    {q:"The topic marker is…", o:["が","は","を","に"], a:1},
    {q:"は as a particle is pronounced…", o:["ha","wa","ba","e"], a:1},
    {q:"Question words like だれ take…", o:["は","が","を","の"], a:1}]},
  {id:"ja-o", cat:"Particles", title:"を (o): direct object", level:1,
   body:"を marks the direct object of a verb.\n• みずを のみます = (I) drink water.\n• ほんを よみます = (I) read a book.\nOnly used as a particle; pronounced 'o'.",
   ex:[["パンを たべます。","(I) eat bread."],["おんがくを ききます。","(I) listen to music."]],
   quiz:[
    {q:"The direct object marker is…", o:["は","が","を","で"], a:2},
    {q:"'read a book': ほん___ よみます", o:["は","を","に","が"], a:1},
    {q:"を is pronounced…", o:["wo always","o","u","silent"], a:1}]},
  {id:"ja-ni-e", cat:"Particles", title:"に and へ: direction & time", level:2,
   body:"• に: destination, specific time, indirect object. がっこうに いきます。7じに おきます。\n• へ (pronounced 'e'): direction, slightly more literary. とうきょうへ いきます。\n• に also marks existence location with います/あります.",
   ex:[["がっこうに いきます。","(I) go to school."],["7じに おきます。","(I) get up at 7."],["ともだちに あげます。","(I) give (it) to a friend."]],
   quiz:[
    {q:"Specific times (7時) take…", o:["を","に","で","は"], a:1},
    {q:"へ as a particle is pronounced…", o:["he","e","we","i"], a:1},
    {q:"'go to school': がっこう___ いきます", o:["を","で","に","が"], a:2}]},
  {id:"ja-de", cat:"Particles", title:"で: place of action & means", level:2,
   body:"• Place where an action happens: レストランで たべます = (I) eat at a restaurant.\n• Means/tool: バスで いきます = (I) go by bus. はしで たべます = eat with chopsticks.\n• Compare: に = existence/destination, で = action location.",
   ex:[["としょかんで べんきょうします。","(I) study at the library."],["でんしゃで いきます。","(I) go by train."]],
   quiz:[
    {q:"'eat at a restaurant': レストラン___", o:["に","で","へ","を"], a:1},
    {q:"'by bus' uses…", o:["を","に","で","は"], a:2},
    {q:"Action location uses…", o:["に","で","が","の"], a:1}]},
  {id:"ja-no", cat:"Particles", title:"の: possession & linking", level:1,
   body:"の links nouns, like 's or 'of'.\n• わたしの ほん = my book.\n• にほんの たべもの = Japanese food.\n• Order: owner の owned.",
   ex:[["わたしの ほん","my book"],["ともだちの くるま","friend's car"],["にほんごの せんせい","Japanese language teacher"]],
   quiz:[
    {q:"'my book' →", o:["ほんのわたし","わたしのほん","わたしはほん","ほんわたしの"], a:1},
    {q:"の works like…", o:["'and'","possessive 's / of","a verb","past tense"], a:1},
    {q:"'teacher of Japanese' →", o:["せんせいのにほんご","にほんごのせんせい","にほんごはせんせい","せんせいにほんご"], a:1}]},
  {id:"ja-desu", cat:"Verbs", title:"です / だ: to be", level:1,
   body:"• です: polite copula. わたしは がくせいです。\n• だ: plain/casual form.\n• Negative: じゃありません / じゃない. Past: でした / だった.\n• です attaches to nouns and na-adjectives.",
   ex:[["わたしは がくせいです。","I am a student."],["これは ほんじゃありません。","This is not a book."],["きのうは あめでした。","Yesterday it was rainy."]],
   quiz:[
    {q:"Polite 'is/am/are' →", o:["だ","です","ます","ある"], a:1},
    {q:"Past of です →", o:["でした","だった only","ですた","じゃない"], a:0},
    {q:"Polite negative of です →", o:["じゃありません","ではない only","ないです only","ません"], a:0}]},
  {id:"ja-masu", cat:"Verbs", title:"ます form: polite present", level:1,
   body:"Polite non-past covers present and future.\n• のみます (drink), たべます (eat), いきます (go).\n• Negative: 〜ません. のみません = don't drink.\n• Past: 〜ました. Past negative: 〜ませんでした.",
   ex:[["まいにち コーヒーを のみます。","(I) drink coffee every day."],["きのう すしを たべました。","Yesterday (I) ate sushi."],["にくを たべません。","(I) don't eat meat."]],
   quiz:[
    {q:"Polite negative ending →", o:["〜ました","〜ません","〜ましょう","〜ますか"], a:1},
    {q:"'ate' (polite) →", o:["たべます","たべません","たべました","たべませんでした"], a:2},
    {q:"ます form covers…", o:["past only","present & future","commands","potential"], a:1}]},
  {id:"ja-groups", cat:"Verbs", title:"Verb groups & dictionary form", level:2,
   body:"Three groups decide how verbs conjugate.\n• Group 1 (u-verbs): のむ→のみます, かく→かきます.\n• Group 2 (ru-verbs): たべる→たべます, みる→みます (drop る, add ます).\n• Irregular: する→します, くる→きます.",
   ex:[["のむ → のみます","to drink"],["たべる → たべます","to eat"],["する → します","to do"]],
   quiz:[
    {q:"たべる is a…", o:["u-verb","ru-verb","irregular","na-adjective"], a:1},
    {q:"ます form of する →", o:["すります","します","するます","せます"], a:1},
    {q:"ます form of かく (u-verb) →", o:["かきます","かくます","かけます","かします"], a:0}]},
  {id:"ja-te", cat:"Verbs", title:"て form: requests & linking", level:2,
   body:"The て form connects actions and makes requests.\n• Requests: 〜てください. みてください = please look.\n• Linking: たべて、ねます = (I) eat and (then) sleep.\n• Ongoing: 〜ています. たべています = is eating.\n• Formation: たべる→たべて; のむ→のんで; かく→かいて; する→して.",
   ex:[["ちょっと まってください。","Please wait a moment."],["テレビを みています。","(I) am watching TV."],["おきて、コーヒーを のみます。","(I) get up and drink coffee."]],
   quiz:[
    {q:"'please eat' →", o:["たべてください","たべますください","たべるください","たべたください"], a:0},
    {q:"〜ています expresses…", o:["past","ongoing action","desire","command"], a:1},
    {q:"て form of のむ →", o:["のみて","のんで","のって","のむて"], a:1}]},
  {id:"ja-adj", cat:"Adjectives", title:"い-adjectives vs. な-adjectives", level:2,
   body:"• い-adjectives end in い and conjugate themselves: たかい (expensive) → たかくない (not expensive) → たかかった (was expensive).\n• な-adjectives need な before a noun and use です forms: しずかな まち (a quiet town), しずかじゃない.\n• Exception: きれい and ゆうめい look like い-adjectives but are な-adjectives.",
   ex:[["たかい ほん","an expensive book"],["しずかな まち","a quiet town"],["この えいがは おもしろかった。","This movie was interesting."]],
   quiz:[
    {q:"Past of たかい →", o:["たかいでした","たかかった","たかくて","たかいだった"], a:1},
    {q:"'quiet town' →", o:["しずかまち","しずかなまち","しずかいまち","しずかのまち"], a:1},
    {q:"きれい is…", o:["an い-adjective","a な-adjective","a verb","a particle"], a:1}]},
  {id:"ja-question", cat:"Sentences", title:"Questions with か", level:1,
   body:"Add か to the end of a polite sentence — no word order change.\n• これは ほんですか。= Is this a book?\n• Question words: なに (what), だれ (who), どこ (where), いつ (when), なぜ/どうして (why), いくら (how much).",
   ex:[["これは なんですか。","What is this?"],["トイレは どこですか。","Where is the toilet?"],["いくらですか。","How much is it?"]],
   quiz:[
    {q:"Questions are made by adding…", o:["の","か","よ","ね"], a:1},
    {q:"'where' →", o:["だれ","いつ","どこ","なに"], a:2},
    {q:"Does word order change in questions?", o:["yes, verb first","yes, subject last","no","only with だれ"], a:2}]},
  {id:"ja-aru-iru", cat:"Verbs", title:"あります / います: existence", level:2,
   body:"• あります: inanimate things exist. つくえの うえに ほんが あります。\n• います: people and animals. こうえんに ねこが います。\n• Pattern: PLACE に THING が あります/います.",
   ex:[["ほんが あります。","There is a book."],["ねこが います。","There is a cat."],["えきの ちかくに ぎんこうが あります。","There is a bank near the station."]],
   quiz:[
    {q:"For animals use…", o:["あります","います","です","ございます"], a:1},
    {q:"'There is a book' →", o:["ほんがいます","ほんがあります","ほんはです","ほんにあります"], a:1},
    {q:"Existence location is marked by…", o:["を","で","に","へ"], a:2}]},
  {id:"ja-tai", cat:"Verbs", title:"〜たい: wanting to do", level:2,
   body:"Attach たい to the ます stem.\n• たべます → たべたい = want to eat.\n• いきます → いきたい = want to go.\n• たい conjugates like an い-adjective: たべたくない (don't want to eat), たべたかった (wanted to eat).",
   ex:[["すしを たべたいです。","(I) want to eat sushi."],["にほんに いきたいです。","(I) want to go to Japan."],["いま はたらきたくない。","(I) don't want to work now."]],
   quiz:[
    {q:"'want to drink' →", o:["のみたい","のむたい","のみたいます","のんでたい"], a:0},
    {q:"Negative of たべたい →", o:["たべたいない","たべたくない","たべませんたい","たべないたい"], a:1},
    {q:"たい conjugates like…", o:["a な-adjective","an い-adjective","a noun","です"], a:1}]},
  {id:"ja-counters", cat:"Numbers", title:"Numbers & counters", level:3,
   body:"Objects are counted with counter words.\n• 〜つ: general things (ひとつ, ふたつ, みっつ…)\n• 〜人 (にん): people — but ひとり (1), ふたり (2).\n• 〜本 (ほん): long objects; 〜枚 (まい): flat objects; 〜匹 (ひき): small animals.\n• りんごを ふたつ ください = two apples, please.",
   ex:[["りんごを みっつ ください。","Three apples, please."],["がくせいが ふたり います。","There are two students."],["ビールを にほん ください。","Two (bottles of) beer, please."]],
   quiz:[
    {q:"General counter for things →", o:["〜人","〜つ","〜枚","〜匹"], a:1},
    {q:"'two people' →", o:["ににん","ふたり","ふたつ","にひき"], a:1},
    {q:"Flat objects (paper, tickets) →", o:["〜本","〜枚","〜匹","〜台"], a:1}]}
  ],
  vocab: [
   {w:"こんにちは",r:"konnichiwa",t:"hello",c:"basics"},{w:"ありがとう",r:"arigatou",t:"thank you",c:"basics"},
   {w:"おねがいします",r:"onegaishimasu",t:"please",c:"basics"},{w:"はい",r:"hai",t:"yes",c:"basics"},
   {w:"いいえ",r:"iie",t:"no",c:"basics"},{w:"さようなら",r:"sayounara",t:"goodbye",c:"basics"},
   {w:"みず",r:"mizu",t:"water",c:"food"},{w:"パン",r:"pan",t:"bread",c:"food"},
   {w:"ぎゅうにゅう",r:"gyuunyuu",t:"milk",c:"food"},{w:"りんご",r:"ringo",t:"apple",c:"food"},
   {w:"コーヒー",r:"koohii",t:"coffee",c:"food"},{w:"ビール",r:"biiru",t:"beer",c:"food"},
   {w:"いえ",r:"ie",t:"house",c:"places"},{w:"まち",r:"machi",t:"city / town",c:"places"},
   {w:"みち",r:"michi",t:"street / way",c:"places"},{w:"えき",r:"eki",t:"train station",c:"places"},
   {w:"みせ",r:"mise",t:"shop",c:"places"},
   {w:"ともだち",r:"tomodachi",t:"friend",c:"people"},{w:"かぞく",r:"kazoku",t:"family",c:"people"},
   {w:"おとこのひと",r:"otoko no hito",t:"man",c:"people"},{w:"おんなのひと",r:"onna no hito",t:"woman",c:"people"},
   {w:"こども",r:"kodomo",t:"child",c:"people"},
   {w:"はなす",r:"hanasu",t:"to speak",c:"verbs"},{w:"たべる",r:"taberu",t:"to eat",c:"verbs"},
   {w:"すむ",r:"sumu",t:"to live (reside)",c:"verbs"},{w:"のむ",r:"nomu",t:"to drink",c:"verbs"},
   {w:"いく",r:"iku",t:"to go",c:"verbs"},{w:"みる",r:"miru",t:"to see / watch",c:"verbs"},
   {w:"する",r:"suru",t:"to do",c:"verbs"},{w:"かう",r:"kau",t:"to buy",c:"verbs"},
   {w:"おおきい",r:"ookii",t:"big",c:"adjectives"},{w:"ちいさい",r:"chiisai",t:"small",c:"adjectives"},
   {w:"いい",r:"ii",t:"good",c:"adjectives"},{w:"わるい",r:"warui",t:"bad",c:"adjectives"},
   {w:"はやい",r:"hayai",t:"fast / early",c:"adjectives"},{w:"きれい",r:"kirei",t:"pretty / clean",c:"adjectives"},
   {w:"きょう",r:"kyou",t:"today",c:"time"},{w:"あした",r:"ashita",t:"tomorrow",c:"time"},
   {w:"きのう",r:"kinou",t:"yesterday",c:"time"},{w:"いま",r:"ima",t:"now",c:"time"},
   {w:"いつも",r:"itsumo",t:"always",c:"time"},{w:"ぜんぜん",r:"zenzen",t:"never (with negative)",c:"time"}
  ]
}
};
