/* Trilingua advanced & native grammar: levels 4 (upper-intermediate), 5 (advanced), 6 (native).
   Same format as data.js rules; merged into DATA at the bottom of this file. */
const GRAMMAR_ADV = {
es: [
{ id:"es-perfect", cat:"Advanced tenses", title:"Present & past perfect", level:4,
  body:"haber + past participle forms the perfect tenses.\n• Present perfect: he/has/ha/hemos/habéis/han + -ado/-ido → he comido (I have eaten).\n• Past perfect: había + participle → había comido (I had eaten).\n• Irregular participles: hecho, dicho, visto, escrito, puesto, vuelto, abierto, muerto.\n• Spain uses the present perfect for today's events; Latin America often prefers the preterite.",
  ex:[["He visto esa película.","I have seen that movie."],["¿Has comido ya?","Have you eaten already?"],["Habíamos salido cuando llamó.","We had left when he called."],["Todavía no he hecho la tarea.","I haven't done the homework yet."]],
  quiz:[{q:"'I have written' =", o:["he escribido","he escrito","había escribir","escribí"], a:1},
        {q:"Past perfect of comer (yo):", o:["he comido","había comido","hube comer","comía"], a:1},
        {q:"Irregular participle of 'ver':", o:["veído","visto","vido","viendo"], a:1}]},
{ id:"es-condicional", cat:"Advanced tenses", title:"Conditional", level:4,
  body:"Infinitive + -ía endings: hablaría, comería, viviría.\n• Polite requests and wishes: Me gustaría… (I would like…).\n• Hypotheticals: Yo no haría eso (I wouldn't do that).\n• Probability in the past: Serían las diez (It was probably ten o'clock).\n• Same irregular stems as the future: tendría, haría, podría, diría.",
  ex:[["Me gustaría viajar más.","I would like to travel more."],["¿Podrías ayudarme?","Could you help me?"],["Dijo que vendría.","He said he would come."],["Sería la una cuando llegó.","It was probably one o'clock when he arrived."]],
  quiz:[{q:"'I would speak' =", o:["hablaré","hablaría","hablara","hablase"], a:1},
        {q:"Conditional stem of 'tener':", o:["ten-","tener-","tendr-","teng-"], a:2},
        {q:"'Serían las diez' expresses…", o:["a command","past probability","a wish","future certainty"], a:1}]},
{ id:"es-imperativo", cat:"Advanced verbs", title:"Commands (imperative)", level:4,
  body:"Affirmative tú: 3rd-person singular form → ¡Habla! ¡Come!\n• Irregular tú commands: di, haz, ve, pon, sal, sé, ten, ven.\n• Negative commands use the subjunctive: ¡No hables! ¡No comas!\n• Usted/ustedes always use the subjunctive: hable, coman.\n• Pronouns attach to affirmative commands: dímelo; but precede negatives: no me lo digas.",
  ex:[["¡Habla más despacio!","Speak more slowly!"],["¡No hables tan rápido!","Don't speak so fast!"],["Dímelo, por favor.","Tell it to me, please."],["¡Hagan la tarea!","Do the homework! (ustedes)"]],
  quiz:[{q:"Negative tú command of hablar:", o:["¡no habla!","¡no hables!","¡no hable!","¡no hablas!"], a:1},
        {q:"Irregular tú command of 'hacer':", o:["hace","haga","haz","hacé"], a:2},
        {q:"Where do pronouns go in '¡dímelo!'?", o:["before the verb","attached to the end","after 'no'","anywhere"], a:1}]},
{ id:"es-obj-pron", cat:"Advanced pronouns", title:"Double object pronouns", level:4,
  body:"Indirect before direct: me lo, te la, nos los.\n• le/les + lo/la/los/las → se lo/se la…: Se lo di (I gave it to him).\n• Pronouns go before conjugated verbs, or attach to infinitives/gerunds/affirmative commands.\n• Clarify se with a él / a ella / a ustedes when ambiguous.",
  ex:[["Te lo doy mañana.","I'll give it to you tomorrow."],["Se la mandé ayer.","I sent it to her yesterday."],["Voy a dártelo.","I'm going to give it to you."],["Está explicándomelo.","He is explaining it to me."]],
  quiz:[{q:"'I gave it (el libro) to him' =", o:["Le lo di","Se lo di","Lo le di","Se le di"], a:1},
        {q:"Order of object pronouns:", o:["direct then indirect","indirect then direct","verb decides","free order"], a:1},
        {q:"'Voy a dár__' (it, to you):", o:["telo","loti","tela","selo"], a:0}]},
{ id:"es-comparativos", cat:"Advanced structures", title:"Comparatives & superlatives", level:4,
  body:"más/menos + adj + que: más alto que (taller than).\n• Equality: tan + adj + como; tanto/a/os/as + noun + como.\n• Irregulars: mejor, peor, mayor, menor.\n• Superlative: el/la más… de: la ciudad más grande de España.\n• Absolute superlative -ísimo: buenísimo, muchísimo.",
  ex:[["Es más alta que su hermano.","She is taller than her brother."],["Tan rápido como un rayo.","As fast as lightning."],["Es el mejor restaurante de la ciudad.","It's the best restaurant in the city."],["La película fue buenísima.","The movie was really good."]],
  quiz:[{q:"'better' =", o:["más bueno","mejor","muy bien","bueníssimo"], a:1},
        {q:"'as tall as' =", o:["tan alto que","más alto como","tan alto como","tanto alto como"], a:2},
        {q:"Superlative of bueno with -ísimo:", o:["buenísimo","bonísimo","buenissimo","mejorísimo"], a:0}]},
{ id:"es-relativos", cat:"Advanced structures", title:"Relative pronouns", level:4,
  body:"que is the all-purpose relative: el libro que leí.\n• quien(es) after prepositions for people: la mujer con quien hablé.\n• el que / el cual for formal or ambiguous cases.\n• cuyo/a/os/as = whose, agrees with the thing owned: el autor cuyas novelas…\n• lo que refers to whole ideas: No entiendo lo que dices.",
  ex:[["El coche que compré es rojo.","The car that I bought is red."],["La persona a quien llamé…","The person whom I called…"],["El escritor cuyo libro ganó…","The writer whose book won…"],["Lo que dijiste es verdad.","What you said is true."]],
  quiz:[{q:"'whose' =", o:["quien","cuyo","que","cual"], a:1},
        {q:"After a preposition, for people use…", o:["que","quien","cuyo","lo que"], a:1},
        {q:"'What you said' =", o:["Que dijiste","Lo que dijiste","Cual dijiste","Quien dijiste"], a:1}]},
{ id:"es-imp-subj", cat:"Advanced subjunctive", title:"Imperfect subjunctive", level:5,
  body:"Formed from the 3rd-person plural preterite minus -ron + -ra endings: hablara, comiera, fuera.\n• Used after past-tense triggers: Quería que vinieras (I wanted you to come).\n• Also after 'como si' (as if): como si fuera fácil.\n• The -se forms (hablase) are equivalent and more literary.\n• Courtesy: Quisiera un café (I would like a coffee).",
  ex:[["Quería que me ayudaras.","I wanted you to help me."],["Habla como si fuera experto.","He talks as if he were an expert."],["Si tuviera tiempo, iría.","If I had time, I would go."],["Quisiera reservar una mesa.","I would like to book a table."]],
  quiz:[{q:"Imperfect subjunctive of 'ser' (yo):", o:["sería","fuera","era","sea"], a:1},
        {q:"'como si' is followed by…", o:["indicative","imperfect subjunctive","infinitive","future"], a:1},
        {q:"'I wanted you to come' =", o:["Quería que vienes","Quería que vengas","Quería que vinieras","Quería que venir"], a:2}]},
{ id:"es-si-clauses", cat:"Advanced subjunctive", title:"Si-clauses (conditionals)", level:5,
  body:"Real: si + present, future → Si llueve, me quedaré.\n• Hypothetical: si + imperfect subjunctive, conditional → Si tuviera dinero, viajaría.\n• Impossible past: si + past perfect subjunctive, conditional perfect → Si hubiera sabido, habría venido.\n• Never present subjunctive directly after si.",
  ex:[["Si llueve, no salimos.","If it rains, we're not going out."],["Si fuera rico, no trabajaría.","If I were rich, I wouldn't work."],["Si hubieras llamado, habría ido.","If you had called, I would have gone."],["Si puedes, ven temprano.","If you can, come early."]],
  quiz:[{q:"'If I were rich, I would travel' =", o:["Si soy rico, viajaría","Si fuera rico, viajaría","Si sea rico, viajaré","Si era rico, viajaba"], a:1},
        {q:"After 'si' you never use…", o:["present indicative","imperfect subjunctive","present subjunctive","past perfect subjunctive"], a:2},
        {q:"'Si hubiera sabido, …' continues with:", o:["habría venido","vendría ayer","vine","venga"], a:0}]},
{ id:"es-se-pasiva", cat:"Advanced structures", title:"Passive & impersonal 'se'", level:5,
  body:"Passive se: Se venden casas (Houses are sold) — verb agrees with the noun.\n• Impersonal se: Se vive bien aquí (One lives well here) — always singular.\n• True passive with ser + participle is formal/written: Fue construido en 1900.\n• Accidental se: Se me olvidaron las llaves (I forgot the keys — 'they forgot themselves on me').",
  ex:[["Se habla español.","Spanish is spoken."],["Se venden coches usados.","Used cars are sold."],["Se me rompió el vaso.","The glass broke on me."],["El puente fue construido en 1920.","The bridge was built in 1920."]],
  quiz:[{q:"'Houses are sold' =", o:["Se vende casas","Se venden casas","Venden se casas","Casas es vendida"], a:1},
        {q:"'Se me olvidaron las llaves' expresses…", o:["blame on me","an unplanned accident","a command","future"], a:1},
        {q:"Impersonal se is always…", o:["plural","singular","feminine","past"], a:1}]},
{ id:"es-subj-clauses", cat:"Advanced subjunctive", title:"Subjunctive in adjective & time clauses", level:5,
  body:"Unknown or nonexistent antecedents take subjunctive: Busco a alguien que hable ruso.\n• Known antecedents take indicative: Conozco a alguien que habla ruso.\n• Future time clauses: cuando/en cuanto/hasta que + subjunctive → Cuando llegues, llámame.\n• Habitual time clauses take indicative: Cuando llego, ceno.",
  ex:[["Busco un piso que tenga balcón.","I'm looking for a flat that has a balcony."],["No hay nadie que lo sepa.","There is no one who knows it."],["Cuando llegues, avísame.","When you arrive, let me know."],["Esperaré hasta que termines.","I'll wait until you finish."]],
  quiz:[{q:"'Busco un libro que ___ útil' (unknown):", o:["es","sea","será","fue"], a:1},
        {q:"'Cuando ___ (llegar, tú) mañana, llámame':", o:["llegas","llegues","llegarás","llegaste"], a:1},
        {q:"Known antecedent takes…", o:["subjunctive","indicative","infinitive","imperative"], a:1}]},
{ id:"es-perf-cond", cat:"Native nuance", title:"Compound conditionals & probability", level:6,
  body:"Future perfect for past probability: Habrá salido (He has probably left).\n• Conditional perfect: Habría ido (I would have gone).\n• Future of probability: ¿Qué hora será? (I wonder what time it is).\n• Deber (de) + infinitive: Debe de estar en casa (He must be at home).",
  ex:[["Habrán llegado ya.","They've probably arrived already."],["Yo lo habría hecho distinto.","I would have done it differently."],["¿Dónde estará Juan?","I wonder where Juan is."],["Debe de ser muy caro.","It must be very expensive."]],
  quiz:[{q:"'They've probably arrived' =", o:["Habrán llegado","Habrían llegado","Han llegado seguro","Llegarán"], a:0},
        {q:"'I would have gone' =", o:["Habré ido","Habría ido","Hubiera ir","Iría"], a:1},
        {q:"'¿Qué hora será?' expresses…", o:["future plan","wondering / probability","command","past habit"], a:1}]},
{ id:"es-diminutivos", cat:"Native nuance", title:"Diminutives & augmentatives", level:6,
  body:"-ito/-ita adds smallness or affection: perrito, cafecito, ahorita.\n• -illo/-illa can be dismissive or lexicalized: cigarrillo, ventanilla.\n• Augmentatives -ón/-ona, -azo/-aza: casona, golazo, buenazo.\n• -azo can also mean a blow: portazo (door slam).\n• Regional flavor: -ico in Colombia/Costa Rica, ahorita timing varies by country.",
  ex:[["¿Tomamos un cafecito?","Shall we have a little coffee?"],["Espérame un momentito.","Wait for me just a moment."],["¡Qué golazo!","What a great goal!"],["Cerró la puerta de un portazo.","He slammed the door."]],
  quiz:[{q:"Diminutive of 'perro':", o:["perrón","perrito","perrazo","perrillo grande"], a:1},
        {q:"'portazo' means…", o:["small door","door slam","doorman","big door"], a:1},
        {q:"-ón/-ona typically makes things…", o:["smaller","bigger/intense","feminine","plural"], a:1}]},
{ id:"es-marcadores", cat:"Native nuance", title:"Discourse markers & fillers", level:6,
  body:"Native speech is glued together with markers:\n• o sea = I mean / that is; es que = the thing is…\n• pues, bueno = well; a ver = let's see; en fin = anyway.\n• vale (Spain), dale (Río de la Plata), órale (Mexico) = OK.\n• ¿no? / ¿verdad? as tag questions; hombre/mujer for emphasis.",
  ex:[["Es que no tengo tiempo.","The thing is, I don't have time."],["O sea, no vienes.","So, I mean, you're not coming."],["Bueno, pues nos vemos mañana.","Well then, see you tomorrow."],["Está bien, ¿no?","It's fine, right?"]],
  quiz:[{q:"'Es que…' introduces…", o:["a question","an excuse/explanation","a command","a wish"], a:1},
        {q:"'o sea' ≈", o:["or else","I mean / that is","maybe","because"], a:1},
        {q:"Which is a Mexican 'OK'?", o:["vale","dale","órale","venga solo España"], a:2}]},
{ id:"es-voseo", cat:"Native nuance", title:"Regional variation & voseo", level:6,
  body:"vos replaces tú in Argentina, Uruguay, much of Central America.\n• Vos forms: vos hablás, comés, vivís; imperative hablá, comé, viví; vos sos (you are).\n• ustedes replaces vosotros everywhere outside Spain.\n• Pronunciation: seseo (LatAm c/z = s), Spain distinguishes; Argentine 'll/y' sounds like 'sh'.\n• Vocabulary shifts: coche/carro/auto, ordenador/computadora, zumo/jugo.",
  ex:[["¿Vos qué pensás?","What do you (vos) think?"],["Vos sos mi mejor amigo.","You are my best friend. (Arg.)"],["Vení para acá.","Come here. (vos imperative)"],["Ustedes hablan muy rápido.","You all speak very fast."]],
  quiz:[{q:"'you are' with vos:", o:["vos eres","vos sos","vos estás ser","vos es"], a:1},
        {q:"'vosotros' is used mainly in…", o:["Argentina","Mexico","Spain","Chile"], a:2},
        {q:"Vos imperative of venir:", o:["ven","vení","venga","vengas"], a:1}]}
],
de: [
{ id:"de-genitiv", cat:"Advanced cases", title:"Genitive case", level:4,
  body:"The genitive marks possession: das Auto meines Vaters (my father's car).\n• Masculine/neuter articles: des, eines + noun ends in -(e)s: des Mannes, des Kindes.\n• Feminine/plural: der, einer (no noun ending): der Frau, der Kinder.\n• Genitive prepositions: wegen, während, trotz, statt, innerhalb, außerhalb.\n• Spoken German often replaces it with von + dative: das Auto von meinem Vater.",
  ex:[["das Haus des Lehrers","the teacher's house"],["wegen des Wetters","because of the weather"],["trotz der Kälte","despite the cold"],["während des Sommers","during the summer"]],
  quiz:[{q:"Genitive of 'der Mann':", o:["dem Mann","des Mannes","den Mann","der Mann"], a:1},
        {q:"Which preposition takes genitive?", o:["mit","wegen","aus","bei"], a:1},
        {q:"Colloquial replacement for genitive:", o:["zu + Akkusativ","von + Dativ","für + Genitiv","an + Dativ"], a:1}]},
{ id:"de-adjdekl", cat:"Advanced structures", title:"Adjective declension (full system)", level:4,
  body:"Adjective endings depend on the article before them.\n• Weak (after der/die/das): der große Mann, den großen Mann — mostly -e/-en.\n• Mixed (after ein/kein/mein): ein großer Mann, ein großes Kind.\n• Strong (no article): großer Mann, großes Kind — adjective carries the case signal.\n• Rule of thumb: the case marker must appear exactly once — on the article or on the adjective.",
  ex:[["der alte Baum","the old tree"],["ein alter Baum","an old tree"],["alter Wein, gutes Essen","old wine, good food"],["mit dem alten Auto","with the old car"]],
  quiz:[{q:"'ein ___ Mann' (groß, nominative):", o:["große","großer","großen","großes"], a:1},
        {q:"After 'der' in nominative, the adjective ends in…", o:["-er","-e","-en","-es"], a:1},
        {q:"Strong endings appear when…", o:["there is no article","after der","after ein","never"], a:0}]},
{ id:"de-passiv", cat:"Advanced verbs", title:"Passive voice", level:4,
  body:"Process passive: werden + Partizip II → Das Haus wird gebaut (is being built).\n• Past: wurde gebaut; perfect: ist gebaut worden.\n• State passive with sein: Die Tür ist geschlossen (is closed).\n• The agent takes von: Der Brief wurde von Anna geschrieben.\n• man is a common active alternative: Man baut hier ein Haus.",
  ex:[["Das Auto wird repariert.","The car is being repaired."],["Die Brücke wurde 1900 gebaut.","The bridge was built in 1900."],["Das Fenster ist geöffnet.","The window is open(ed)."],["Der Kuchen wurde von Oma gebacken.","The cake was baked by grandma."]],
  quiz:[{q:"'The house is being built' =", o:["Das Haus ist gebaut","Das Haus wird gebaut","Das Haus baut","Das Haus wurde bauen"], a:1},
        {q:"The agent in a passive sentence takes…", o:["mit","von","durch nur","bei"], a:1},
        {q:"State passive uses…", o:["werden","sein","haben","machen"], a:1}]},
{ id:"de-futur", cat:"Advanced tenses", title:"Future I & II", level:4,
  body:"Futur I: werden + infinitive → Ich werde kommen.\n• Present tense + time word is more common for plans: Ich komme morgen.\n• Futur I also expresses assumptions: Er wird wohl krank sein (He's probably sick).\n• Futur II for completed future / past probability: Er wird es vergessen haben (He will have / has probably forgotten it).",
  ex:[["Ich werde dich anrufen.","I will call you."],["Morgen fahre ich nach Berlin.","Tomorrow I'm going to Berlin."],["Sie wird wohl im Büro sein.","She is probably at the office."],["Bis Freitag werde ich es beendet haben.","By Friday I will have finished it."]],
  quiz:[{q:"Futur I is formed with…", o:["haben + Infinitiv","werden + Infinitiv","sein + Partizip","würden + Infinitiv"], a:1},
        {q:"'Er wird wohl krank sein' expresses…", o:["a plan","an assumption","a command","a wish"], a:1},
        {q:"Futur II of 'vergessen' (er):", o:["wird vergessen","wird vergessen haben","hat vergessen werden","würde vergessen"], a:1}]},
{ id:"de-relativ", cat:"Advanced structures", title:"Relative clauses", level:4,
  body:"Relative pronouns look like der/die/das (dative plural: denen).\n• Gender/number from the noun, case from the clause: Der Mann, den ich sehe…\n• The verb goes to the end of the relative clause.\n• With prepositions: die Frau, mit der ich arbeite.\n• was after alles, etwas, nichts: alles, was ich weiß.",
  ex:[["Der Mann, der dort steht…","The man who is standing there…"],["Das Buch, das ich lese…","The book that I'm reading…"],["Die Frau, mit der ich spreche…","The woman I'm talking with…"],["Alles, was du sagst…","Everything you say…"]],
  quiz:[{q:"'Der Mann, ___ ich sehe' :", o:["der","den","dem","dessen"], a:1},
        {q:"After 'etwas' use…", o:["das","was","wer","welches"], a:1},
        {q:"In a relative clause the verb goes…", o:["second","first","to the end","anywhere"], a:2}]},
{ id:"de-konj2", cat:"Advanced mood", title:"Konjunktiv II (hypotheticals)", level:5,
  body:"Unreal situations and polite requests.\n• würde + infinitive is the standard form: Ich würde gehen.\n• Common one-word forms: wäre, hätte, könnte, müsste, wüsste, käme, ginge.\n• Conditionals: Wenn ich Zeit hätte, würde ich kommen.\n• Politeness: Könnten Sie mir helfen? Ich hätte gern einen Kaffee.\n• Past unreal: hätte/wäre + Partizip II → Ich wäre gekommen.",
  ex:[["Wenn ich reich wäre…","If I were rich…"],["Ich hätte gern ein Bier.","I would like a beer."],["Könntest du mir helfen?","Could you help me?"],["Ich wäre gekommen, wenn du angerufen hättest.","I would have come if you had called."]],
  quiz:[{q:"Konjunktiv II of 'sein' (ich):", o:["sei","wäre","würde sein nur","war"], a:1},
        {q:"'I would have come' =", o:["Ich würde kommen","Ich wäre gekommen","Ich hätte gekommen","Ich kam"], a:1},
        {q:"Polite request uses…", o:["Präsens","Konjunktiv II","Imperativ nur","Futur II"], a:1}]},
{ id:"de-konj1", cat:"Advanced mood", title:"Konjunktiv I (reported speech)", level:5,
  body:"News and formal writing report speech with Konjunktiv I.\n• Formed from the infinitive stem + -e endings: er sagte, er habe keine Zeit.\n• sein is irregular: ich sei, er sei, sie seien.\n• If Konjunktiv I looks like the indicative, Konjunktiv II steps in: sie sagten, sie hätten…\n• Signals distance: the speaker doesn't vouch for the claim.",
  ex:[["Er sagte, er sei krank.","He said he was sick."],["Sie behauptet, sie habe nichts gesehen.","She claims she saw nothing."],["Die Zeitung schreibt, es gebe Probleme.","The paper writes there are problems."],["Man sagte, sie hätten kein Geld.","They said they had no money."]],
  quiz:[{q:"Konjunktiv I of 'sein' (er):", o:["ist","sei","wäre","war"], a:1},
        {q:"Konjunktiv I mainly appears in…", o:["commands","reported speech","questions","wishes only"], a:1},
        {q:"If K I = indicative, use…", o:["Präteritum","Konjunktiv II","Imperativ","Futur"], a:1}]},
{ id:"de-infinitiv", cat:"Advanced structures", title:"Infinitive clauses: zu, um…zu", level:5,
  body:"zu + infinitive after many verbs/expressions: Ich hoffe, dich zu sehen.\n• um…zu = in order to: Ich lerne, um zu bestehen.\n• ohne…zu = without …ing; statt…zu = instead of …ing.\n• Separable verbs insert zu: anzurufen, aufzustehen.\n• Modal verbs and gehen/sehen/lassen take bare infinitives: Ich kann schwimmen.",
  ex:[["Ich habe vergessen, ihn anzurufen.","I forgot to call him."],["Sie lernt Deutsch, um in Berlin zu arbeiten.","She learns German (in order) to work in Berlin."],["Er ging, ohne zu bezahlen.","He left without paying."],["Es ist schwer, früh aufzustehen.","It's hard to get up early."]],
  quiz:[{q:"'in order to' =", o:["ohne…zu","um…zu","statt…zu","für…zu"], a:1},
        {q:"zu with 'anrufen':", o:["zu anrufen","anzurufen","anrufen zu","zurufen an"], a:1},
        {q:"After modal verbs the infinitive is…", o:["with zu","bare (no zu)","a participle","nominalized"], a:1}]},
{ id:"de-plusquam", cat:"Advanced tenses", title:"Plusquamperfekt & nachdem", level:5,
  body:"Past-before-past: hatte/war + Partizip II.\n• Ich hatte gegessen, bevor er kam (I had eaten before he came).\n• nachdem forces it: Nachdem sie gegangen war, rief er an.\n• Movement/change verbs take war: war gefahren, war eingeschlafen.\n• Timeline: Plusquamperfekt → Präteritum/Perfekt → Präsens → Futur.",
  ex:[["Ich hatte das Buch schon gelesen.","I had already read the book."],["Nachdem er gegessen hatte, ging er.","After he had eaten, he left."],["Sie war schon abgefahren.","She had already departed."],["Wir hatten uns lange nicht gesehen.","We hadn't seen each other for a long time."]],
  quiz:[{q:"Plusquamperfekt of 'gehen' (er):", o:["ist gegangen","war gegangen","hatte gegangen","ging"], a:1},
        {q:"'nachdem' typically pairs Plusquamperfekt with…", o:["Futur","Präteritum","Konjunktiv","Imperativ"], a:1},
        {q:"'I had eaten' =", o:["Ich habe gegessen","Ich hatte gegessen","Ich war gegessen","Ich aß gehabt"], a:1}]},
{ id:"de-partizip", cat:"Native structures", title:"Participles as adjectives & extended attributes", level:5,
  body:"Partizip I (infinitive + d) = ongoing: das schlafende Kind (the sleeping child).\n• Partizip II = completed/passive: die geschlossene Tür.\n• Written German stacks whole phrases before the noun: die von der Regierung geplante Reform (the reform planned by the government).\n• Unpack them as relative clauses when reading: die Reform, die von der Regierung geplant wurde.",
  ex:[["das weinende Baby","the crying baby"],["ein gebrauchtes Auto","a used car"],["die im Jahr 1900 gebaute Brücke","the bridge built in 1900"],["der viel diskutierte Plan","the much-discussed plan"]],
  quiz:[{q:"Partizip I of 'schlafen':", o:["geschlafen","schlafend","schlief","schlafene"], a:1},
        {q:"'die geschlossene Tür' uses…", o:["Partizip I","Partizip II","Infinitiv","Konjunktiv"], a:1},
        {q:"Extended attributes are typical of…", o:["casual speech","written/formal German","dialects","children's speech"], a:1}]},
{ id:"de-nominal", cat:"Native style", title:"Nominal style & Funktionsverbgefüge", level:6,
  body:"Formal German turns verbs into nouns.\n• zur Verfügung stehen = to be available; in Frage kommen = to be an option.\n• eine Entscheidung treffen = to decide; Kritik üben = to criticize.\n• Nominalization: das Lesen, die Entwicklung, beim Einkaufen.\n• Officialese chains: die Durchführung der Überprüfung der Unterlagen — unpack into verbs to understand.",
  ex:[["Das steht Ihnen zur Verfügung.","That is at your disposal."],["Wir müssen eine Entscheidung treffen.","We have to make a decision."],["Das kommt nicht in Frage.","That is out of the question."],["Beim Lesen ist mir ein Fehler aufgefallen.","While reading, I noticed a mistake."]],
  quiz:[{q:"'eine Entscheidung treffen' =", o:["to meet a decision","to decide","to hit a choice","to cancel"], a:1},
        {q:"'zur Verfügung stehen' =", o:["to stand up","to be available","to be forbidden","to be standing"], a:1},
        {q:"Nominal style is typical of…", o:["formal/administrative texts","baby talk","songs","dialect"], a:0}]},
{ id:"de-partikeln", cat:"Native nuance", title:"Modal particles: doch, mal, ja, eben", level:6,
  body:"Tiny words that carry attitude — untranslatable but essential.\n• doch: contradiction or encouragement: Komm doch mit! Das stimmt doch nicht!\n• mal: softens: Guck mal. Warte mal.\n• ja: shared knowledge/surprise: Das ist ja toll! Du weißt ja, wie er ist.\n• eben/halt: resignation: Das ist eben so.\n• schon: reassurance: Das wird schon klappen.",
  ex:[["Komm doch mit!","Come along, why don't you!"],["Guck mal!","Take a look!"],["Das ist ja interessant!","Well, that's interesting!"],["Das ist halt so.","That's just how it is."]],
  quiz:[{q:"'Das wird schon klappen' — schon adds…", o:["annoyance","reassurance","doubt","speed"], a:1},
        {q:"'eben/halt' expresses…", o:["enthusiasm","resignation","fear","politeness"], a:1},
        {q:"Which particle softens requests?", o:["ja","mal","eben","erst"], a:1}]},
{ id:"de-konnektoren", cat:"Native style", title:"Advanced connectors", level:6,
  body:"Written argumentation uses two-part and adverbial connectors.\n• zwar…aber: admittedly…but. je…desto: the more…the more.\n• entweder…oder; weder…noch; sowohl…als auch.\n• Adverbial connectors take position 1, verb second: Dennoch kam er. Folglich, allerdings, hingegen, demnach.\n• indem = by …ing: Man lernt, indem man übt.",
  ex:[["Je mehr ich lerne, desto besser verstehe ich.","The more I learn, the better I understand."],["Zwar ist es teuer, aber es lohnt sich.","It's expensive, admittedly, but worth it."],["Weder er noch sie wussten es.","Neither he nor she knew it."],["Man verbessert sich, indem man Fehler macht.","One improves by making mistakes."]],
  quiz:[{q:"'the more…the more' =", o:["je…desto","zwar…aber","weder…noch","erst…dann"], a:0},
        {q:"'indem' expresses…", o:["time","means/method","contrast","place"], a:1},
        {q:"After 'dennoch' at position 1, the verb is…", o:["at the end","second","first","optional"], a:1}]},
{ id:"de-umgang", cat:"Native nuance", title:"Colloquial German & regional flavor", level:6,
  body:"Spoken German bends the rules.\n• Dropped e: ich hab', geh'n; wir ham (haben).\n• weil + verb-second in speech: Ich bleib zu Hause, weil ich bin müde (nonstandard but common).\n• tun as helper: Ich tu das mal eben machen (colloquial).\n• Regional greetings: Moin (north), Grüß Gott/Servus (south/Austria), Grüezi (Switzerland).\n• Diminutives: -chen/-lein standard; -le (Swabian), -erl (Austria), -li (Switzerland).",
  ex:[["Ich hab keine Zeit.","I don't have time. (colloquial)"],["Moin! Na, alles klar?","Hi! Everything OK? (north)"],["Servus, wie geht's dir?","Hi, how are you? (south)"],["Ein Bisschen — ein bissel — ein bisserl.","A little (standard — regional variants)."]],
  quiz:[{q:"'Moin' is typical of…", o:["Bavaria","northern Germany","Switzerland","Saxony only"], a:1},
        {q:"Standard diminutive endings:", o:["-chen/-lein","-le/-erl","-li/-la","-ito/-ita"], a:0},
        {q:"'weil + verb second' is…", o:["standard written German","common colloquial speech","impossible","Konjunktiv"], a:1}]}
],
ja: [
{ id:"ja-potential", cat:"Advanced verbs", title:"Potential form (can do)", level:4,
  body:"Ru-verbs: drop る, add られる: たべる → たべられる (can eat; colloquially たべれる).\n• U-verbs: change final -u to -eru: のむ → のめる, かく → かける.\n• Irregular: する → できる, くる → こられる.\n• The object often takes が: すしが たべられます.\n• 〜ことができる is a more formal alternative: およぐことができます.",
  ex:[["にほんごが はなせます。","I can speak Japanese."],["ここで きっぷが かえます。","You can buy tickets here."],["あした こられますか。","Can you come tomorrow?"],["うんてんすることが できます。","I am able to drive."]],
  quiz:[{q:"Potential of のむ:", o:["のまれる","のめる","のみられる","のむできる"], a:1},
        {q:"Potential of する:", o:["すれる","される","できる","しられる"], a:2},
        {q:"With potential verbs the object often takes…", o:["を","が","に","へ"], a:1}]},
{ id:"ja-volitional", cat:"Advanced verbs", title:"Volitional form (let's / shall)", level:4,
  body:"Ru-verbs: る → よう: たべよう (let's eat).\n• U-verbs: -u → -ou: いく → いこう, のむ → のもう.\n• Polite: 〜ましょう: いきましょう (let's go); 〜ましょうか offers help.\n• 〜(よ)うとおもう = I think I'll…: りゅうがくしようとおもいます.\n• 〜(よ)うとする = to try/attempt to do.",
  ex:[["いっしょに いこう。","Let's go together."],["てつだいましょうか。","Shall I help you?"],["らいねん にほんへ いこうとおもいます。","I think I'll go to Japan next year."],["ねようとしたとき、でんわがなった。","Just as I was about to sleep, the phone rang."]],
  quiz:[{q:"Volitional of いく:", o:["いくよう","いこう","いけよう","いきましょ"], a:1},
        {q:"'Shall I help?' =", o:["てつだいます","てつだいましょうか","てつだえます","てつだって"], a:1},
        {q:"〜ようとおもう means…", o:["I must","I think I will","I can","I want you to"], a:1}]},
{ id:"ja-obligation", cat:"Advanced structures", title:"Obligation & permission", level:4,
  body:"〜なければならない / 〜なきゃ = must: いかなければなりません (I must go).\n• 〜なくてもいい = don't have to: こなくてもいいです.\n• 〜てもいい = may / it's OK to: たべてもいいですか.\n• 〜てはいけない = must not: ここで たばこを すってはいけません.\n• Casual: 〜ないと, 〜なきゃ, 〜ちゃだめ.",
  ex:[["もう いかなければなりません。","I have to go now."],["あした こなくてもいいですよ。","You don't have to come tomorrow."],["ここに すわってもいいですか。","May I sit here?"],["しゃしんを とってはいけません。","You must not take photos."]],
  quiz:[{q:"'must go' =", o:["いってもいい","いかなくてもいい","いかなければならない","いってはいけない"], a:2},
        {q:"'may I…?' uses…", o:["〜てはいけない","〜てもいいですか","〜なければ","〜なくても"], a:1},
        {q:"〜なくてもいい means…", o:["must","must not","don't have to","cannot"], a:2}]},
{ id:"ja-giving", cat:"Advanced structures", title:"Giving & receiving (あげる・くれる・もらう)", level:4,
  body:"あげる: I/we give outward. くれる: someone gives to me/my group. もらう: to receive.\n• てform + あげる/くれる/もらう = doing favors: てつだってくれた (he helped me).\n• 〜てもらう = to have someone do something for you: おしえてもらいました.\n• Honorific/humble versions: さしあげる, くださる, いただく.\n• Choosing the right verb encodes the direction of the favor — a core of natural Japanese.",
  ex:[["ともだちが ほんを くれました。","A friend gave me a book."],["せんせいに おしえてもらいました。","I had the teacher teach me."],["おとうとに おかしを あげた。","I gave my little brother sweets."],["みちを おしえてくださいました。","He kindly showed me the way. (honorific)"]],
  quiz:[{q:"Someone gives TO ME:", o:["あげる","くれる","もらう","やる"], a:1},
        {q:"'I had him fix it' =", o:["なおしてあげた","なおしてくれた","なおしてもらった","なおされた"], a:2},
        {q:"Humble 'receive':", o:["くださる","いただく","さしあげる","たまわる のみ"], a:1}]},
{ id:"ja-comparison", cat:"Advanced structures", title:"Comparison & superlatives", level:4,
  body:"AはBより + adj = A is more…than B: これは それより やすいです.\n• BよりAのほうが…: コーヒーより おちゃのほうが すきです.\n• Questions: AとBと、どちらが…? Answer: 〜のほうが.\n• Superlative: 〜の中で いちばん…: かぞくの中で いちばん せがたかい.\n• 〜ほど…ない = not as…as: きょうは きのうほど さむくない.",
  ex:[["でんしゃは バスより はやいです。","Trains are faster than buses."],["なつより ふゆのほうが すきです。","I like winter more than summer."],["クラスの中で いちばん わかい。","The youngest in the class."],["ことしは きょねんほど あつくない。","This year isn't as hot as last year."]],
  quiz:[{q:"'A is cheaper than B' =", o:["AはBより やすい","AよりBは やすい","AはBほど やすい","AとBが やすい"], a:0},
        {q:"'the most…' =", o:["もっと","いちばん","ほど","ぐらい"], a:1},
        {q:"〜ほど…ない means…", o:["more than","not as…as","the same as","because"], a:1}]},
{ id:"ja-tari-nagara", cat:"Advanced structures", title:"〜たり〜たり and 〜ながら", level:4,
  body:"〜たり〜たりする lists sample activities: えいがをみたり、かいものをしたりしました (I did things like watching a movie and shopping).\n• Formed from the た-form + り.\n• 〜ながら = while doing (same subject): おんがくをききながら べんきょうします.\n• The main action is the second verb with ながら.\n• 〜あいだ(に) = during/while for longer spans.",
  ex:[["やすみのひは ねたり ほんをよんだりします。","On days off I sleep, read, and so on."],["あるきながら はなしましょう。","Let's talk while walking."],["たべながら テレビをみる。","To watch TV while eating."],["なつやすみのあいだに りょこうした。","I traveled during summer vacation."]],
  quiz:[{q:"〜たり〜たり expresses…", o:["exact sequence","a sample list of actions","obligation","ability"], a:1},
        {q:"'while listening to music' =", o:["おんがくをきくながら","おんがくをききながら","おんがくをきいてながら","おんがくをきけながら"], a:1},
        {q:"With ながら, the main action is…", o:["the first verb","the second verb","either","omitted"], a:1}]},
{ id:"ja-passive", cat:"Advanced verbs", title:"Passive (られる)", level:5,
  body:"Ru-verbs: る → られる; U-verbs: -u → -areru: よむ → よまれる.\n• Direct passive: せんせいに ほめられました (I was praised by the teacher).\n• Suffering passive — something done to your inconvenience: あめに ふられた (I got rained on).\n• The doer takes に.\n• する → される, くる → こられる.",
  ex:[["どろぼうに さいふを とられた。","My wallet was stolen by a thief."],["せんせいに しかられました。","I was scolded by the teacher."],["あかちゃんに なかれて、ねられなかった。","The baby cried on me and I couldn't sleep."],["このほんは よく よまれています。","This book is widely read."]],
  quiz:[{q:"Passive of よむ:", o:["よめる","よまれる","よもう","よみられる"], a:1},
        {q:"The doer in a passive sentence takes…", o:["が","を","に","で"], a:2},
        {q:"あめに ふられた expresses…", o:["ability","an unwelcome event","a wish","politeness"], a:1}]},
{ id:"ja-causative", cat:"Advanced verbs", title:"Causative & causative-passive", level:5,
  body:"Causative = make/let someone do. Ru-verbs: る → させる; U-verbs: -u → -aseru: いく → いかせる.\n• こどもに やさいを たべさせる (make the child eat vegetables).\n• 'Let' with permission nuance: あそばせてあげた (I let him play).\n• Causative-passive = be made to do: ざんぎょうさせられた (I was made to work overtime).\n• する → させる → させられる.",
  ex:[["むすこに へやを そうじさせた。","I made my son clean his room."],["すきなだけ あそばせた。","I let him play as much as he liked."],["じょうしに またされました。","I was kept waiting by my boss."],["おさけを のまされた／のませられた。","I was made to drink."]],
  quiz:[{q:"Causative of たべる:", o:["たべられる","たべさせる","たべさられる","たべそう"], a:1},
        {q:"'I was made to wait' =", o:["またせた","まった","またされた","まてる"], a:2},
        {q:"Causative of する:", o:["される","させる","すらせる","できさせる"], a:1}]},
{ id:"ja-conditionals", cat:"Advanced structures", title:"Four conditionals: と・ば・たら・なら", level:5,
  body:"と = automatic result: はるになると、はながさく (when spring comes, flowers bloom).\n• ば = general/logical if: やすければ かいます (if it's cheap, I'll buy it).\n• たら = one-time if/when, most versatile: ついたら でんわして.\n• なら = 'if that's the case': にほんに いくなら、JRパスをかったほうがいい.\n• Only たら can express unexpected discoveries: あけたら、ねこがいた.",
  ex:[["このボタンをおすと、ドアがあきます。","If you press this button, the door opens."],["じかんがあれば、いきます。","If I have time, I'll go."],["やすかったら、かいましょう。","If it's cheap, let's buy it."],["おんせんなら、はこねがいいですよ。","If it's hot springs (you want), Hakone is good."]],
  quiz:[{q:"Automatic cause-effect uses…", o:["と","なら","ば のみ","たら のみ"], a:0},
        {q:"'If you're going to Japan…' (topic-if):", o:["いくと","いけば","いくなら","いったら のみ"], a:2},
        {q:"ば-form of やすい:", o:["やすいば","やすければ","やすかれば","やすいなら"], a:1}]},
{ id:"ja-hearsay", cat:"Advanced nuance", title:"そう・よう・らしい・みたい", level:5,
  body:"Four ways to hedge:\n• 〜そうだ (stem) = looks like: おいしそう (looks tasty).\n• 〜そうだ (plain form) = I heard: あめがふるそうです (I hear it will rain).\n• 〜ようだ/〜みたい = seems (from evidence): だれもいないようだ.\n• 〜らしい = apparently (hearsay/typicality): かれはやめるらしい; おとこらしい (manly).",
  ex:[["このケーキ、おいしそう！","This cake looks delicious!"],["ニュースによると、たいふうがくるそうだ。","According to the news, a typhoon is coming."],["かぜをひいたみたいです。","It seems I've caught a cold."],["あのみせは ゆうめいらしい。","That shop is apparently famous."]],
  quiz:[{q:"'looks tasty' =", o:["おいしいそう","おいしそう","おいしいらしい","おいしいよう"], a:1},
        {q:"'I heard it will rain' =", o:["あめがふりそうです","あめがふるそうです","あめらしいふる","あめのようにふる"], a:1},
        {q:"おとこらしい means…", o:["seems to be a man","manly","I heard he's a man","wants to be a man"], a:1}]},
{ id:"ja-keigo", cat:"Native register", title:"Keigo: honorific & humble language", level:6,
  body:"Three layers: 丁寧語 (polite です/ます), 尊敬語 (honors others), 謙譲語 (humbles yourself).\n• Honorific: いらっしゃる (be/go/come), おっしゃる (say), めしあがる (eat), ごらんになる (look).\n• Humble: まいる (go/come), もうす (say), いただく (eat/receive), はいけんする (look).\n• Patterns: お+stem+になる (honorific), お+stem+する (humble): おまちしております.\n• Essential in business, shops, and with superiors.",
  ex:[["しゃちょうは いらっしゃいますか。","Is the president in? (honorific)"],["たなかと もうします。","My name is Tanaka. (humble)"],["どうぞ めしあがってください。","Please eat. (honorific)"],["しりょうを はいけんしました。","I looked at the materials. (humble)"]],
  quiz:[{q:"Honorific 'to say':", o:["もうす","おっしゃる","はなされる","いう"], a:1},
        {q:"Humble 'to go':", o:["いらっしゃる","まいる","おいでになる","いかれる"], a:1},
        {q:"謙譲語 (humble) lowers…", o:["the listener","yourself/your group","everyone","the topic"], a:1}]},
{ id:"ja-written", cat:"Native register", title:"Written style: である and formal patterns", level:6,
  body:"Essays, papers, and news use である instead of です: これは問題である.\n• Formal negatives: 〜ではない, 〜ぬ (知らぬ), 〜ず(に) = without doing: 食べずに寝た.\n• 〜ざるをえない = have no choice but to: 認めざるをえない.\n• 〜べき = should (norms): 学生は勉強すべきだ.\n• 〜における/〜に関する/〜によって are written-style connectors.",
  ex:[["日本における教育の問題である。","It is a problem of education in Japan."],["何も言わずに出て行った。","He left without saying anything."],["中止せざるをえなかった。","We had no choice but to cancel."],["約束は守るべきだ。","Promises should be kept."]],
  quiz:[{q:"Written-style copula:", o:["だよ","である","です のみ","じゃん"], a:1},
        {q:"〜ずに means…", o:["after doing","without doing","while doing","in order to"], a:1},
        {q:"〜ざるをえない =", o:["must not","have no choice but to","might","want to"], a:1}]},
{ id:"ja-onomatopoeia", cat:"Native nuance", title:"Onomatopoeia (ぎおんご・ぎたいご)", level:6,
  body:"Japanese uses thousands of sound/state words, usually reduplicated.\n• Sounds (擬音語): ざあざあ (pouring rain), ぺらぺら (fluent/flipping pages).\n• States (擬態語): きらきら (sparkling), ふわふわ (fluffy), いらいら (irritated).\n• どきどき (heart pounding), わくわく (excited), ぐっすり (sound asleep).\n• Often + と before verbs or + する: きらきら(と)ひかる; どきどきする.\n• Voiced consonants feel heavier: ころころ (light rolling) vs ごろごろ (heavy rolling/thunder/lazing).",
  ex:[["あめが ざあざあ ふっている。","The rain is pouring down."],["ほしが きらきら ひかる。","The stars sparkle."],["しけんのまえは どきどきする。","My heart pounds before exams."],["にちようびは いえで ごろごろした。","On Sunday I lazed around at home."]],
  quiz:[{q:"'fluffy' =", o:["ぺらぺら","ふわふわ","ざあざあ","ごろごろ"], a:1},
        {q:"どきどき describes…", o:["rain","a pounding heart","sparkle","snoring"], a:1},
        {q:"Voiced ごろごろ vs ころころ feels…", o:["lighter","heavier/bigger","faster","politer"], a:1}]},
{ id:"ja-dialects", cat:"Native nuance", title:"Spoken nuance: particles & dialects", level:6,
  body:"Sentence-final particles carry attitude: ね (agreement), よ (assertion), かな (I wonder), ぞ/ぜ (rough emphasis), わ (soft, also Kansai), っけ (trying to recall).\n• Casual contractions: 〜ちゃう (してしまう), 〜てる (ている), 〜なきゃ (なければ).\n• Kansai-ben: おおきに (thanks), あかん (no good), 〜へん (negative: わからへん), や instead of だ (そうや).\n• Tokyo standard is understood everywhere, but recognizing dialects unlocks TV and daily talk.",
  ex:[["それ、いいね。","That's nice, isn't it."],["もう たべちゃった。","I (regrettably) already ate it."],["なんだっけ？","What was it again?"],["これ、あかんわ。","This is no good. (Kansai)"]],
  quiz:[{q:"〜ちゃう is a contraction of…", o:["ている","てしまう","ておく","てみる"], a:1},
        {q:"Kansai negative of わかる:", o:["わからない のみ","わからへん","わからぬ","わかりまへん のみ"], a:1},
        {q:"かな expresses…", o:["a command","wondering","certainty","anger"], a:1}]}
]
};
/* merge into the app's rule set */
for (const l of ["es","de","ja"]) DATA[l].grammar.push(...GRAMMAR_ADV[l]);
