/* Japanese reading & writing course: a structured plan from zero to reading.
   Rendered as a special page in the Grammar tab when Japanese is selected. */
const JA_READING = {
title: "Reading & writing — the complete plan",
intro: "Japanese uses three scripts together. This course takes you from zero to reading real Japanese in a defined order: hiragana first (2 weeks), katakana next (1–2 weeks), then kanji in frequency order, forever. Each stage below has the full reference charts, a study method, and a weekly schedule at the end.",
sections: [
{ h:"Stage 0 — how the writing system fits together",
  ps:[
  "Every Japanese sentence mixes three scripts with fixed jobs. Hiragana (ひらがな) writes grammar: particles, verb/adjective endings, and native words without common kanji. Katakana (カタカナ) writes loanwords, foreign names, onomatopoeia and emphasis. Kanji (漢字) write the content cores: noun stems, verb roots, adjective roots. 私はコーヒーを飲みます uses all three in nine characters.",
  "Both kana sets are syllabaries: each symbol is one mora (a rhythm beat), not a letter. There are only 46 basic symbols per set, plus regular modifications — so kana are a bounded, fully learnable system in days, not months. Kanji are open-ended (~2,100 in daily use), which is why they're staged last and learned by frequency.",
  "Romaji (Latin letters) is scaffolding. This app shows romaji next to kana so you're never blocked, but every hour reading kana directly pays back double. Rule of thumb: after Stage 1, stop reading the romaji line first."],
  tables:[
  {title:"The three scripts", head:["Script","Writes","Character count","Example"],
   rows:[["Hiragana","grammar, native words","46 + marks","たべます, は, を"],
         ["Katakana","loanwords, names, emphasis","46 + marks","コーヒー, アメリカ"],
         ["Kanji","word stems / meaning","~2,100 common","食, 水, 大"]]}]},
{ h:"Stage 1 — Hiragana (weeks 1–2)",
  ps:[
  "Learn the chart row by row in gojūon order (the table below reads top-to-bottom, right column first in Japanese books, but left-to-right works fine for learners). Do two rows per day: day 1 あ-row + か-row, day 2 さ-row + た-row, and so on — all 46 in five days, then five days of consolidation.",
  "Method per row: (1) look at the character and a mnemonic image (あ looks like an Antenna on a roof), (2) write it 10 times with correct stroke order while saying the sound aloud, (3) immediately read mixed syllables from rows you know. Writing by hand is not optional in this stage — the motor memory is what makes recognition instant.",
  "After the base 46, the modifications are mechanical, not new learning: dakuten ゛ voices a consonant (か ka → が ga), handakuten ゜ turns h into p (は ha → ぱ pa), small ゃゅょ fuse with i-row kana (き + ゃ = きゃ kya), small っ doubles the following consonant (きって kitte), and long vowels double the vowel (おかあさん) — except long o is usually written with う (おう → ō, e.g. ありがとう).",
  "Exit test for Stage 1: read any word in this app's vocabulary list aloud in under 2 seconds per word without looking at the romaji."],
  tables:[
  {title:"Hiragana — the 46 basics (gojūon)", head:["Row","a","i","u","e","o"],
   rows:[["—","あ a","い i","う u","え e","お o"],
         ["k","か ka","き ki","く ku","け ke","こ ko"],
         ["s","さ sa","し shi","す su","せ se","そ so"],
         ["t","た ta","ち chi","つ tsu","て te","と to"],
         ["n","な na","に ni","ぬ nu","ね ne","の no"],
         ["h","は ha","ひ hi","ふ fu","へ he","ほ ho"],
         ["m","ま ma","み mi","む mu","め me","も mo"],
         ["y","や ya","—","ゆ yu","—","よ yo"],
         ["r","ら ra","り ri","る ru","れ re","ろ ro"],
         ["w","わ wa","—","—","—","を o (particle)"],
         ["n","ん n","","","",""]]},
  {title:"Dakuten & handakuten (voiced sounds)", head:["Base row","+゛","+゜"],
   rows:[["か き く け こ","が ぎ ぐ げ ご (g)","—"],
         ["さ し す せ そ","ざ じ ず ぜ ぞ (z/j)","—"],
         ["た ち つ て と","だ ぢ づ で ど (d)","—"],
         ["は ひ ふ へ ほ","ば び ぶ べ ぼ (b)","ぱ ぴ ぷ ぺ ぽ (p)"]]},
  {title:"Yōon (combined sounds)", head:["+ゃ","+ゅ","+ょ"],
   rows:[["きゃ kya / ぎゃ gya","きゅ kyu / ぎゅ gyu","きょ kyo / ぎょ gyo"],
         ["しゃ sha / じゃ ja","しゅ shu / じゅ ju","しょ sho / じょ jo"],
         ["ちゃ cha","ちゅ chu","ちょ cho"],
         ["にゃ nya / ひゃ hya","にゅ nyu / ひゅ hyu","にょ nyo / ひょ hyo"],
         ["みゃ mya / りゃ rya","みゅ myu / りゅ ryu","みょ myo / りょ ryo"]]},
  {title:"Special mechanics", head:["Mark","Effect","Example"],
   rows:[["small っ","doubles next consonant (hold one beat)","きって kitte — stamp"],
         ["long vowel","hold two beats","おばあさん obaasan"],
         ["long o","usually written with う","ありがとう arigatou"],
         ["ん before b/p/m","sounds like m","しんぶん shimbun"]]}]},
{ h:"Stage 2 — Katakana (weeks 3–4)",
  ps:[
  "Katakana encodes the same 46 sounds with different shapes. Learn it the same way — two rows per day — but with a twist: practice by reading real loanwords, because katakana words are often English in disguise: コーヒー koohii (coffee), テレビ terebi (TV), ホテル hoteru. Decoding them is instant vocabulary.",
  "Katakana has extra machinery for foreign sounds: the long-vowel bar ー (コーヒー), and extended combos like ファ fa, フィ fi, ティ ti, ディ di, ウィ wi, ヴ vu — built by pairing a kana with a small vowel.",
  "Spend deliberate time on the lookalike pairs: シ shi vs ツ tsu (shi's strokes are horizontal-ish and drawn upward; tsu's are vertical-ish and drawn downward), ソ so vs ン n (same logic). Write them side by side until the difference is automatic.",
  "Exit test: read a restaurant menu's katakana items (in photos or apps) at natural speed."],
  tables:[
  {title:"Katakana — the 46 basics", head:["Row","a","i","u","e","o"],
   rows:[["—","ア a","イ i","ウ u","エ e","オ o"],
         ["k","カ ka","キ ki","ク ku","ケ ke","コ ko"],
         ["s","サ sa","シ shi","ス su","セ se","ソ so"],
         ["t","タ ta","チ chi","ツ tsu","テ te","ト to"],
         ["n","ナ na","ニ ni","ヌ nu","ネ ne","ノ no"],
         ["h","ハ ha","ヒ hi","フ fu","ヘ he","ホ ho"],
         ["m","マ ma","ミ mi","ム mu","メ me","モ mo"],
         ["y","ヤ ya","—","ユ yu","—","ヨ yo"],
         ["r","ラ ra","リ ri","ル ru","レ re","ロ ro"],
         ["w","ワ wa","—","—","—","ヲ o"],
         ["n","ン n","","","",""]]},
  {title:"Dangerous lookalikes", head:["Pair","How to tell them apart"],
   rows:[["シ shi / ツ tsu","shi: strokes lie flat, last stroke sweeps UP. tsu: strokes stand up, last stroke sweeps DOWN"],
         ["ソ so / ン n","so: top stroke vertical, sweep from top. n: stroke flat, sweep from bottom"],
         ["ク ku / ケ ke / タ ta","ta = ku + extra stroke; ke has the long horizontal"],
         ["コ ko / ユ yu / ロ ro","ro is closed, ko is open at bottom-left, yu has the protruding base"]]},
  {title:"Extended katakana for foreign sounds", head:["Combo","Sound","Example"],
   rows:[["ファ / フィ / フェ / フォ","fa fi fe fo","ファイル fairu — file"],
         ["ティ / ディ","ti di","パーティー paatii — party"],
         ["ウィ / ウェ / ウォ","wi we wo","ウェブ webu — web"],
         ["ヴ","v","ヴァイオリン vaiorin"],
         ["ー","long vowel","ケーキ keeki — cake"]]}]},
{ h:"Stage 3 — reading mechanics & pronunciation",
  ps:[
  "Three spelling exceptions carry over from history and appear in every sentence: the topic particle は is read wa, the direction particle へ is read e, and the object particle を is read o. Your eye must learn to switch reading based on grammatical role — this app's sentence-building exercises drill exactly that.",
  "Rhythm: Japanese is mora-timed. とうきょう is four beats (to-u-kyo-u), not two syllables. The small っ is a full silent beat. Getting the beat right matters more for being understood than getting pitch right.",
  "Vowel devoicing: u and i often whisper between voiceless consonants or at the end: です sounds like 'des', ます like 'mas', すき like 'ski'. Pitch accent exists (はし can mean bridge or chopsticks by pitch) but treat it as a polish topic: copy audio, don't memorize charts at this stage — use the 🔊 buttons throughout this app and shadow what you hear."],
  tables:[
  {title:"Particle spelling exceptions", head:["Written","Read","Role","Example"],
   rows:[["は","wa","topic","わたしは → watashi wa"],
         ["へ","e","direction","がっこうへ → gakkou e"],
         ["を","o","object","ほんを → hon o"]]},
  {title:"Mora counting", head:["Word","Beats","Breakdown"],
   rows:[["とうきょう","4","と・う・きょ・う"],["きって","3","き・っ・て"],
         ["しんぶん","4","し・ん・ぶ・ん"],["コーヒー","4","コ・ー・ヒ・ー"]]}]},
{ h:"Stage 4 — Kanji: the system before the characters",
  ps:[
  "Kanji become manageable once you see the system. Most kanji have two reading families: on'yomi (Chinese-derived, used in compounds: 水 sui in 水曜日) and kun'yomi (native, used standalone or with okurigana: 水 mizu). Rule of thumb: kanji+kanji compound → on'yomi; kanji alone or with hiragana tail → kun'yomi. Exceptions exist; learn readings through words, never as isolated lists.",
  "Kanji are built from ~200 recurring components (radicals). 語 = 言 (speech) + 五 + 口. Knowing 50 common radicals turns memorizing 'random strokes' into reading 'ingredient lists' — and often hints at meaning (氵 = water: 海, 泳, 池) or sound (青 sei in 晴, 清, 精).",
  "Okurigana are the hiragana tails that carry conjugation: 食べる, 食べます, 食べた — the kanji 食 holds the meaning 'eat', hiragana does the grammar. Furigana are small kana printed above kanji in learner and children's material — your bridge to reading real content early.",
  "Study method: 10 new kanji per week through words you already know from this app's vocabulary. For each kanji: learn the components, one kun word and one on compound, and write it 5 times. Review with spaced repetition — the same schedule this app uses for vocabulary."],
  tables:[
  {title:"Starter radicals (learn these first)", head:["Radical","Meaning","Appears in"],
   rows:[["亻(人)","person","休 rest, 何 what"],["氵(水)","water","海 sea, 泳 swim"],
         ["木","tree","森 forest, 校 school"],["口","mouth/opening","話 speak, 名 name"],
         ["日","sun/day","時 time, 明 bright"],["月","moon/flesh","服 clothes, 期 period"],
         ["言","speech","語 language, 読 read"],["糸","thread","紙 paper, 線 line"],
         ["扌(手)","hand","持 hold, 押 push"],["辶","movement","道 road, 週 week"],
         ["心","heart","思 think, 悪 bad"],["宀","roof","家 house, 安 cheap"]]},
  {title:"First 40 kanji (weeks 5–8, 10/week)", head:["Kanji","Kun-reading","On-reading","Meaning"],
   rows:[["一","ひと(つ)","イチ","one"],["二","ふた(つ)","ニ","two"],["三","みっ(つ)","サン","three"],
         ["人","ひと","ジン・ニン","person"],["日","ひ","ニチ・ジツ","day, sun"],["月","つき","ゲツ・ガツ","moon, month"],
         ["火","ひ","カ","fire"],["水","みず","スイ","water"],["木","き","モク","tree"],["金","かね","キン","gold, money"],
         ["土","つち","ド","earth"],["年","とし","ネン","year"],["時","とき","ジ","time"],["分","わ(かる)","フン・ブン","minute; understand"],
         ["今","いま","コン","now"],["大","おお(きい)","ダイ","big"],["小","ちい(さい)","ショウ","small"],["中","なか","チュウ","middle, inside"],
         ["上","うえ","ジョウ","up"],["下","した","カ・ゲ","down"],["山","やま","サン","mountain"],["川","かわ","セン","river"],
         ["口","くち","コウ","mouth"],["目","め","モク","eye"],["手","て","シュ","hand"],["足","あし","ソク","foot, leg"],
         ["車","くるま","シャ","car"],["門","かど","モン","gate"],["先","さき","セン","ahead, previous"],["生","い(きる)","セイ","life, birth"],
         ["学","まな(ぶ)","ガク","study"],["校","—","コウ","school"],["食","た(べる)","ショク","eat"],["飲","の(む)","イン","drink"],
         ["見","み(る)","ケン","see"],["行","い(く)","コウ","go"],["来","く(る)","ライ","come"],["何","なに","カ","what"],
         ["本","もと","ホン","book, origin"],["語","かた(る)","ゴ","language, word"]]},
  {title:"Kanji 41–80 (weeks 9–12)", head:["Kanji","Meaning","Kanji","Meaning"],
   rows:[["男 man","女 woman","子 child","父 father"],
         ["母 mother","友 friend","名 name","私 I"],
         ["白 white","黒 black","赤 red","青 blue"],
         ["高 tall/expensive","安 cheap/safe","新 new","古 old"],
         ["長 long","多 many","少 few","早 early"],
         ["天 sky","気 spirit/air","雨 rain","電 electricity"],
         ["駅 station","道 road","町 town","店 shop"],
         ["国 country","外 outside","東 east","西 west"],
         ["南 south","北 north","右 right","左 left"],
         ["読 read","書 write","聞 hear/ask","話 speak"]]}]},
{ h:"Stage 5 — stroke order & handwriting practice",
  ps:[
  "Stroke order isn't pedantry: it makes characters legible at speed, makes handwriting recognizable to input apps, and — most usefully — makes NEW characters easier to remember because your hand follows universal rules instead of memorizing per character.",
  "Practice routine (10 minutes/day): pick the day's kana or kanji, write each large on grid paper following stroke order, then five more times shrinking to normal size, then close the reference and write from memory while saying the reading aloud. Air-writing with a finger during idle time reinforces the same motor pattern.",
  "Digital balance: you will TYPE Japanese far more often than write it (typing uses romaji → kana conversion, so kana knowledge is enough). Handwrite everything through the kana stages and the first 100 kanji; after that, recognition-focused study with occasional handwriting is a reasonable trade-off."],
  tables:[
  {title:"The eight stroke-order rules", head:["#","Rule","Example"],
   rows:[["1","top before bottom","三: top → middle → bottom"],
         ["2","left before right","川: left → middle → right"],
         ["3","horizontal before vertical when they cross","十: ― then |"],
         ["4","center before symmetric wings","小: middle → left → right"],
         ["5","outside before inside…","国: frame first"],
         ["6","…but close the frame last","国: bottom stroke after the inside"],
         ["7","left-falling before right-falling","人: ノ then ㇏"],
         ["8","piercing strokes last","中: the vertical goes last"]]}]},
{ h:"Stage 6 — the reading ladder (months 2–12)",
  ps:[
  "Read at the right difficulty and reading teaches itself. The ladder: (1) this app's vocabulary and sentences — all kana with romaji backup; (2) kana-only easy readers and children's picture books; (3) material with full furigana: NHK News Web Easy, graded readers level 0–1, kids' manga like Yotsuba&!; (4) graded readers 2–3 and manga with partial furigana; (5) native text with a pop-up dictionary. Move up when you understand ~90% comfortably.",
  "Intensive vs extensive: do BOTH. Intensive = one short text, look up everything, understand 100% (10 min/day). Extensive = longer, easier material, look up almost nothing, keep moving (as much as you enjoy). Extensive reading builds the speed; intensive builds the precision.",
  "Inside this app: switch your eyes to kana-first in the Vocab tab, use every 🔊 button to bind sound to spelling, and use sentence building (Practice tab) as reading-order training — Japanese word order becomes automatic when your hands build it."],
  tables:[
  {title:"Reading ladder", head:["Level","Material","You're ready when"],
   rows:[["1","this app: vocab + sentences","kana readable, slowly"],
         ["2","kana-only readers, picture books","kana at speed"],
         ["3","NHK Easy, graded readers 0–1, furigana manga","~80 kanji known"],
         ["4","graded readers 2–3, partial furigana","~300 kanji"],
         ["5","native text + pop-up dictionary","~600+ kanji, N4 grammar"]]}]},
{ h:"The 12-week schedule",
  ps:[
  "Twenty to thirty focused minutes a day, six days a week, plus your normal app practice sessions. Weeks 1–4 are fixed; from week 5 the kanji rhythm (10/week through known words) continues indefinitely — after week 12 you'll have both kana solid and ~80 kanji, enough for ladder level 3.",
  "If you miss days, don't compress — shift the plan. Consistency beats intensity everywhere in language learning, and doubly so in writing systems."],
  tables:[
  {title:"Week by week", head:["Week","Focus","Daily core task","Milestone"],
   rows:[["1","hiragana rows あ–の","2 rows: write ×10, read mixed drills","25 hiragana"],
         ["2","hiragana rows は–ん + marks","2 rows + dakuten/yōon; read app vocab in kana","all hiragana read"],
         ["3","katakana rows ア–ノ","2 rows; decode 10 loanwords/day","25 katakana"],
         ["4","katakana rest + lookalikes","シツソン drills; menu reading","all kana at speed"],
         ["5","radicals + kanji 1–10","numbers & elements; write ×5 each","first compounds: 日本, 水曜日"],
         ["6","kanji 11–20","time & size words","read dates and prices"],
         ["7","kanji 21–30","body & nature; intensive reading starts","one NHK Easy headline/day"],
         ["8","kanji 31–40","verbs 食飲見行来 through app vocab","40 kanji"],
         ["9","kanji 41–50","people & family","read self-introductions"],
         ["10","kanji 51–60","colors & adjectives","describe things in writing"],
         ["11","kanji 61–70","places & directions","read simple signs/maps"],
         ["12","kanji 71–80 + review week","re-test all kana + 80 kanji","ladder level 3 unlocked"]]}]}
]};
