/* Sentence-building exercises. t = tiles in correct order, en = translation,
   level = difficulty tier (unlocks like grammar rules), rule = linked grammar rule,
   hint = shown after the first wrong tile. */
const SENTENCES = {
es: [
{ t:["yo","hablo","español"], en:"I speak Spanish", level:1, rule:"es-present",
  hint:"Subject → verb → object. 'hablar' with yo ends in -o." },
{ t:["la","casa","es","grande"], en:"The house is big", level:1, rule:"es-ser-estar",
  hint:"'ser' for permanent qualities: la casa ES grande." },
{ t:["tengo","dos","hermanos"], en:"I have two brothers", level:1, rule:"es-present",
  hint:"The subject pronoun is usually dropped: (yo) tengo…" },
{ t:["el","café","está","caliente"], en:"The coffee is hot", level:1, rule:"es-ser-estar",
  hint:"'estar' for states and conditions: el café ESTÁ caliente." },
{ t:["no","como","carne"], en:"I don't eat meat", level:1, rule:"es-negation",
  hint:"'no' goes directly before the verb." },
{ t:["me","gusta","la","música"], en:"I like music", level:2, rule:"es-gustar",
  hint:"Literally 'music pleases me': me gusta + singular noun." },
{ t:["me","gustan","los","perros"], en:"I like dogs", level:2, rule:"es-gustar",
  hint:"Plural thing liked → gustan: me gustan los perros." },
{ t:["me","levanto","a","las","siete"], en:"I get up at seven", level:2, rule:"es-reflexive",
  hint:"Reflexive pronoun before the verb: me levanto." },
{ t:["ayer","comí","paella"], en:"Yesterday I ate paella", level:2, rule:"es-preterite",
  hint:"Completed past action → preterite: comí." },
{ t:["cuando","era","niño","jugaba","mucho"], en:"When I was a child I played a lot", level:2, rule:"es-imperfect",
  hint:"Ongoing past description/habit → imperfect: era, jugaba." },
{ t:["mañana","voy","a","viajar"], en:"Tomorrow I am going to travel", level:3, rule:"es-future",
  hint:"Near future: ir + a + infinitive." },
{ t:["este","regalo","es","para","ti"], en:"This gift is for you", level:3, rule:"es-porpara",
  hint:"'para' = destination/recipient." },
{ t:["gracias","por","tu","ayuda"], en:"Thanks for your help", level:3, rule:"es-porpara",
  hint:"'por' = cause/exchange: gracias POR…" },
{ t:["quiero","que","vengas","conmigo"], en:"I want you to come with me", level:3, rule:"es-subjunctive",
  hint:"querer que + subjunctive: …que VENGAS." },
{ t:["he","visto","esa","película"], en:"I have seen that movie", level:4, rule:"es-perfect",
  hint:"Present perfect: he + participle; 'visto' is irregular." },
{ t:["me","gustaría","viajar","más"], en:"I would like to travel more", level:4, rule:"es-condicional",
  hint:"Conditional for wishes: gustaría." },
{ t:["no","hables","tan","rápido"], en:"Don't speak so fast", level:4, rule:"es-imperativo",
  hint:"Negative commands use the subjunctive: no hables." },
{ t:["se","lo","di","a","ella"], en:"I gave it to her", level:4, rule:"es-obj-pron",
  hint:"le + lo becomes SE lo; indirect before direct." },
{ t:["si","tuviera","dinero","viajaría"], en:"If I had money I would travel", level:5, rule:"es-si-clauses",
  hint:"Hypothetical: si + imperfect subjunctive, + conditional." },
{ t:["quería","que","me","ayudaras"], en:"I wanted you to help me", level:5, rule:"es-imp-subj",
  hint:"Past trigger → imperfect subjunctive: ayudaras." },
{ t:["aquí","se","habla","español"], en:"Spanish is spoken here", level:5, rule:"es-se-pasiva",
  hint:"Passive 'se': se habla + singular noun." },
{ t:["busco","un","piso","que","tenga","balcón"], en:"I'm looking for a flat that has a balcony", level:6, rule:"es-subj-clauses",
  hint:"Unknown antecedent → subjunctive: que TENGA." },
{ t:["habrán","llegado","ya"], en:"They have probably arrived already", level:6, rule:"es-perf-cond",
  hint:"Future perfect for past probability: habrán llegado." },
{ t:["es","que","no","tengo","tiempo"], en:"The thing is, I don't have time", level:6, rule:"es-marcadores",
  hint:"'Es que…' introduces an explanation or excuse." }
],
de: [
{ t:["ich","lerne","Deutsch"], en:"I am learning German", level:1, rule:"de-present",
  hint:"Verb in second position: ich LERNE Deutsch." },
{ t:["das","Haus","ist","groß"], en:"The house is big", level:1, rule:"de-present",
  hint:"Subject → verb (position 2) → rest." },
{ t:["ich","habe","einen","Hund"], en:"I have a dog", level:1, rule:"de-akkusativ",
  hint:"'haben' takes accusative: einEN Hund (masculine)." },
{ t:["heute","gehe","ich","ins","Kino"], en:"Today I am going to the cinema", level:2, rule:"de-wordorder",
  hint:"If 'heute' is first, the verb stays second and the subject follows: heute GEHE ich." },
{ t:["ich","gebe","dem","Mann","das","Buch"], en:"I give the man the book", level:2, rule:"de-dativ",
  hint:"Recipient in dative: DEM Mann; thing in accusative." },
{ t:["ich","kann","gut","schwimmen"], en:"I can swim well", level:2, rule:"de-modal",
  hint:"Modal verb second, infinitive at the end: kann … schwimmen." },
{ t:["er","kommt","nicht","mit"], en:"He is not coming along", level:2, rule:"de-separable",
  hint:"Separable prefix goes to the end: kommt … MIT." },
{ t:["ich","stehe","um","sieben","auf"], en:"I get up at seven", level:2, rule:"de-separable",
  hint:"aufstehen splits: stehe … auf." },
{ t:["ich","weiß","dass","du","recht","hast"], en:"I know that you are right", level:3, rule:"de-nebensatz",
  hint:"After 'dass' the verb moves to the end: …recht HAST." },
{ t:["gestern","habe","ich","Pizza","gegessen"], en:"Yesterday I ate pizza", level:3, rule:"de-perfekt",
  hint:"Perfekt: haben in position 2, participle at the end." },
{ t:["sie","ist","nach","Berlin","gefahren"], en:"She went to Berlin", level:3, rule:"de-perfekt",
  hint:"Movement verbs form the Perfekt with SEIN: ist … gefahren." },
{ t:["ich","warte","auf","den","Bus"], en:"I am waiting for the bus", level:3, rule:"de-akkusativ",
  hint:"warten auf + accusative: auf DEN Bus." },
{ t:["das","Auto","meines","Vaters","ist","alt"], en:"My father's car is old", level:4, rule:"de-genitiv",
  hint:"Genitive: meines Vaters = of my father." },
{ t:["das","Haus","wird","gebaut"], en:"The house is being built", level:4, rule:"de-passiv",
  hint:"Passive: werden + participle at the end." },
{ t:["der","Mann","den","ich","sehe","ist","alt"], en:"The man whom I see is old", level:4, rule:"de-relativ",
  hint:"Relative pronoun in accusative: DEN ich sehe; verb at clause end." },
{ t:["ein","großer","Hund","schläft","dort"], en:"A big dog is sleeping there", level:4, rule:"de-adjdekl",
  hint:"After 'ein' (masc. nominative) the adjective takes -er: großER." },
{ t:["wenn","ich","Zeit","hätte","würde","ich","kommen"], en:"If I had time I would come", level:5, rule:"de-konj2",
  hint:"Konjunktiv II: hätte in the wenn-clause, würde + infinitive in the main clause." },
{ t:["er","sagte","er","sei","krank"], en:"He said he was sick", level:5, rule:"de-konj1",
  hint:"Reported speech uses Konjunktiv I: er SEI krank." },
{ t:["ich","habe","vergessen","ihn","anzurufen"], en:"I forgot to call him", level:5, rule:"de-infinitiv",
  hint:"zu inside a separable verb: anZUrufen." },
{ t:["nachdem","er","gegessen","hatte","ging","er"], en:"After he had eaten, he left", level:5, rule:"de-plusquam",
  hint:"nachdem + Plusquamperfekt (gegessen hatte), then Präteritum." },
{ t:["wir","müssen","eine","Entscheidung","treffen"], en:"We have to make a decision", level:6, rule:"de-nominal",
  hint:"Funktionsverbgefüge: eine Entscheidung TREFFEN = entscheiden." },
{ t:["komm","doch","mal","mit"], en:"Come along, why don't you", level:6, rule:"de-partikeln",
  hint:"Particles soften: doch (encouragement) + mal (casual)." },
{ t:["je","mehr","ich","lerne","desto","besser","verstehe","ich"], en:"The more I learn, the better I understand", level:6, rule:"de-konnektoren",
  hint:"je + verb-end clause, desto + comparative + verb second." },
{ t:["die","1900","gebaute","Brücke","ist","schön"], en:"The bridge built in 1900 is beautiful", level:6, rule:"de-partizip",
  hint:"Extended attribute: die [1900 gebaute] Brücke." }
],
ja: [
{ t:["わたし","は","がくせい","です"], en:"I am a student", level:1, rule:"ja-desu",
  hint:"Topic + は, then noun + です." },
{ t:["これ","は","ほん","です"], en:"This is a book", level:1, rule:"ja-wa-ga",
  hint:"は marks the topic: これは." },
{ t:["わたし","は","みず","を","のみます"], en:"I drink water", level:1, rule:"ja-o",
  hint:"を marks the direct object; the verb comes last." },
{ t:["ねこ","が","います"], en:"There is a cat", level:1, rule:"ja-aru-iru",
  hint:"Living things exist with います; が marks what exists." },
{ t:["がっこう","へ","いきます"], en:"I go to school", level:2, rule:"ja-ni-e",
  hint:"へ (or に) marks the direction of movement." },
{ t:["としょかん","で","べんきょうします"], en:"I study at the library", level:2, rule:"ja-de",
  hint:"で marks the place where an action happens." },
{ t:["これ","は","わたし","の","ほん","です"], en:"This is my book", level:2, rule:"ja-no",
  hint:"の links owner to thing: わたしの ほん." },
{ t:["すし","を","たべたい","です"], en:"I want to eat sushi", level:2, rule:"ja-tai",
  hint:"Verb stem + たい = want to do." },
{ t:["にほんご","は","むずかしくない","です"], en:"Japanese is not difficult", level:2, rule:"ja-adj",
  hint:"い-adjective negative: むずかしい → むずかしくない." },
{ t:["ちょっと","まって","ください"], en:"Please wait a moment", level:3, rule:"ja-te",
  hint:"て-form + ください = polite request." },
{ t:["テレビ","を","みて","ねます"], en:"I watch TV and then sleep", level:3, rule:"ja-te",
  hint:"て-form links actions in sequence: みて、ねます." },
{ t:["りんご","を","みっつ","かいました"], en:"I bought three apples", level:3, rule:"ja-counters",
  hint:"Counter after the object: りんごを みっつ." },
{ t:["おんがく","を","ききながら","べんきょうします"], en:"I study while listening to music", level:4, rule:"ja-tari-nagara",
  hint:"stem + ながら = while doing; the main action comes last." },
{ t:["にほんご","が","はなせます"], en:"I can speak Japanese", level:4, rule:"ja-potential",
  hint:"Potential form; the object usually takes が." },
{ t:["いっしょ","に","いきましょう"], en:"Let's go together", level:4, rule:"ja-volitional",
  hint:"〜ましょう = let's…" },
{ t:["もう","いかなければ","なりません"], en:"I have to go now", level:4, rule:"ja-obligation",
  hint:"〜なければなりません = must." },
{ t:["ともだち","が","ほん","を","くれました"], en:"A friend gave me a book", level:4, rule:"ja-giving",
  hint:"Someone gives TO ME → くれる." },
{ t:["でんしゃ","は","バス","より","はやい","です"], en:"Trains are faster than buses", level:4, rule:"ja-comparison",
  hint:"AはBより + adjective = A is more … than B." },
{ t:["せんせい","に","ほめられました"], en:"I was praised by the teacher", level:5, rule:"ja-passive",
  hint:"Passive られる; the doer takes に." },
{ t:["こども","に","やさい","を","たべさせます"], en:"I make the child eat vegetables", level:5, rule:"ja-causative",
  hint:"Causative させる; the person made to act takes に." },
{ t:["やすかったら","かいます"], en:"If it is cheap, I will buy it", level:5, rule:"ja-conditionals",
  hint:"たら-conditional: やすい → やすかったら." },
{ t:["あめ","が","ふる","そうです"], en:"I hear it will rain", level:5, rule:"ja-hearsay",
  hint:"Plain form + そうです = hearsay (I heard that…)." },
{ t:["しゃちょう","は","いらっしゃいます","か"], en:"Is the president in?", level:6, rule:"ja-keigo",
  hint:"Honorific いらっしゃる replaces いる for others." },
{ t:["なにも","いわず","に","でていきました"], en:"He left without saying anything", level:6, rule:"ja-written",
  hint:"〜ずに = without doing (written/formal style)." },
{ t:["ほし","が","きらきら","ひかります"], en:"The stars sparkle", level:6, rule:"ja-onomatopoeia",
  hint:"Mimetic word before the verb: きらきら ひかる." },
{ t:["もう","たべちゃった"], en:"I already ate it (casual)", level:6, rule:"ja-dialects",
  hint:"〜ちゃった = casual contraction of 〜てしまった." }
]
};
